/*
**
* BEGIN_COPYRIGHT
*
* This file is part of SciDB.
* Copyright (C) 2008-2014 SciDB, Inc.
*
* SciDB is free software: you can redistribute it and/or modify
* it under the terms of the AFFERO GNU General Public License as published by
* the Free Software Foundation.
*
* SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
* INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
* NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
* the AFFERO GNU General Public License for the complete license terms.
*
* You should have received a copy of the AFFERO GNU General Public License
* along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
*
* END_COPYRIGHT
*/

ERRMSG(SCIDB_E_NO_ERROR,                             "No errors");

ERRMSG(SCIDB_LE_UNKNOWN_ERROR,                       "Unknown error: %1%");

ERRMSG(SCIDB_LE_ERRNS_ALREADY_REGISTERED,            "Namespace '%1%' is already registered");

ERRMSG(SCIDB_LE_AGGREGATE_NOT_FOUND,                 "Aggregate name '%1%' is not registered in the system");
ERRMSG(SCIDB_LE_AGGREGATE_DOESNT_SUPPORT_ASTERISK,   "Aggregate '%1%' does not support asterisk");
ERRMSG(SCIDB_LE_AGGREGATE_DOESNT_SUPPORT_TYPE,       "Aggregate '%1%' does not support input type '%2%'");
ERRMSG(SCIDB_LE_UNHANDLED_VAR_PARAMETER,             "Operator '%1%' cannot handle variable number of parameters");
ERRMSG(SCIDB_LE_NO_MEMORY_FOR_VALUE,                 "Not enough memory for new value");
ERRMSG(SCIDB_LE_THREAD_EVENT_ERROR,                  "Error state '%1%' detected in event wait");
ERRMSG(SCIDB_LE_THREAD_SEMAPHORE_ERROR,              "Error state '%1%' detected in semaphore enter");
ERRMSG(SCIDB_LE_CANT_LOAD_MODULE,                    "Cannot load module '%1%', dlopen returned '%2%");
ERRMSG(SCIDB_LE_WRONG_MODULE_VERSION,                "Plugin version does not match the version of SciDB. The plugin %1% has version %2%.%3%.%4%.%5% but SciDB version is %6%");
ERRMSG(SCIDB_LE_CANT_FIND_SYMBOL,                    "Cannot find symbol '%1%', dlsym returned '%2%'");
ERRMSG(SCIDB_LE_INPUTS_MUST_BE_BEFORE_PARAMS,        "Error in operator '%1%'. All inputs must appear before other parameters");
ERRMSG(SCIDB_LE_VAR_MUST_BE_AFTER_PARAMS,            "Error in operator '%1%'. Optional parameters must appear last");
ERRMSG(SCIDB_LE_UNEXPECTED_GETREPARTSCHEMA,          "Unexpected getRepartSchema that is not overwritten");
ERRMSG(SCIDB_LE_PWRITE_ERROR,                        "pwrite failed to write %1% byte(s) to the position %2% with error %3%");
ERRMSG(SCIDB_LE_PREAD_ERROR,                         "pread failed to read %1% byte(s) from position %2% with error %3%");
ERRMSG(SCIDB_LE_OPERATOR_NOT_FOUND,                  "Operator '%1%' not found");
ERRMSG(SCIDB_LE_ARRAY_DOESNT_EXIST,                  "Array '%1%' does not exist");
ERRMSG(SCIDB_LE_ARRAYID_DOESNT_EXIST,                "Array with id '%1%' does not exist");
ERRMSG(SCIDB_LE_CANT_OPEN_FILE,                      "Cannot open file '%1%' errno %2%");
ERRMSG(SCIDB_LE_INSTANCE_DOESNT_EXIST,               "Instance with id %1% does not exist");
ERRMSG(SCIDB_LE_ATTRIBUTE_DOESNT_EXIST,              "Attribute with id %1% does not exist in array '%2%'");
ERRMSG(SCIDB_LE_DUPLICATE_ATTRIBUTE_NAME,            "Cannot create attribute '%1%'; name collides with existing object");
ERRMSG(SCIDB_LE_ILLEGAL_OPERATION,                   "Illegal operation: %1%");
ERRMSG(SCIDB_LE_NOT_IMPLEMENTED,                     "Feature '%1%' not yet implemented");
ERRMSG(SCIDB_LE_NO_CURRENT_ELEMENT,                  "No current element");
ERRMSG(SCIDB_LE_OPERATION_FAILED,                    "Operation '%1%' failed");
ERRMSG(SCIDB_LE_UNKNOWN_CONFIG_OPTION,               "Unknown config option '%1%'");
ERRMSG(SCIDB_LE_ERROR_NEAR_CONFIG_OPTION,            "Error '%1%' near config option '%2%'");
ERRMSG(SCIDB_LE_ERROR_IN_CONFIGURATION_FILE,         "Error '%1%' in configuration file");
ERRMSG(SCIDB_LE_FILE_NOT_FOUND,                      "File '%1%' not found");
ERRMSG(SCIDB_LE_ARRAY_VERSION_DOESNT_EXIST,          "Specified version of array '%1%' does not exist");
ERRMSG(SCIDB_LE_CANT_SEND_RECEIVE,                   "Cannot send or receive network messages");
ERRMSG(SCIDB_LE_CONNECTION_ERROR,                    "Error #%1% when connecting to %2%:%3%");
ERRMSG(SCIDB_LE_FUNCTION_NOT_FOUND,                  "Function '%1%' not found");
ERRMSG(SCIDB_LE_TYPE_CONVERSION_ERROR,               "Cannot convert type '%1%' into '%2%'");
ERRMSG(SCIDB_LE_TYPE_CONVERSION_ERROR2,              "Cannot convert '%1%' of type '%2%' into '%3%'");
ERRMSG(SCIDB_LE_REF_NOT_FOUND,                       "Reference '%1%' not found");
ERRMSG(SCIDB_LE_ERROR_IN_UDF,                        "Error '%1%' in UDF '%2%'");
ERRMSG(SCIDB_LE_UNKNOWN_ERROR_IN_UDF,                "Unknown error in UDF '%1%'");
ERRMSG(SCIDB_LE_TYPE_NOT_REGISTERED,                 "Type '%1%' is not registered");
ERRMSG(SCIDB_LE_TYPE_ALREADY_REGISTERED,             "Type '%1%' is already registered");
ERRMSG(SCIDB_LE_DIMENSION_NOT_EXIST,                 "Dimension '%1%' does not exist");
ERRMSG(SCIDB_LE_ATTRIBUTE_NOT_EXIST,                 "Attribute '%1%' does not exist");
ERRMSG(SCIDB_LE_CANT_FIND_CONVERTER,                 "Cannot find converter from type '%1%' to '%2%'");
ERRMSG(SCIDB_LE_CANT_FIND_IMPLICIT_CONVERTER,        "Cannot find implicit converter from type '%1%' to '%2%'");
ERRMSG(SCIDB_LE_PARAMETER_TYPE_ERROR,                "Operator expected expression of type '%1%' but passed nonconvertable type '%2%'");
ERRMSG(SCIDB_LE_DISTRIBUTION_SPECIFICATION_ERROR,    "Multi-child operators with specific distribution requirements not supported");
ERRMSG(SCIDB_LE_DISTRIBUTION_SPECIFICATION_ERROR2,   "Operators with more than two input arrays may only require distribution ANY or COLLOCATED");
ERRMSG(SCIDB_LE_LOGICAL_OP_DOESNT_EXIST,             "Logical operator '%1%' does not exist");
ERRMSG(SCIDB_LE_PHYSICAL_OP_DOESNT_EXIST,            "Physical operator '%1%' for logical operator '%2%' does not exist");
ERRMSG(SCIDB_LE_LOGICAL_OP_ALREADY_REGISTERED,       "Logical operator '%1%' already registered");
ERRMSG(SCIDB_LE_PHYSICAL_OP_ALREADY_REGISTERED,      "Physical operator '%1%' for logical operator '%2%' already registered");
ERRMSG(SCIDB_LE_QUERY_CANCELLED,                      "Query %1% was cancelled"); // tigor: this error code is reserved to indicate query abort state
ERRMSG(SCIDB_LE_NO_QUORUM,                           "Instance liveness has changed");
ERRMSG(SCIDB_LE_QUERY_NOT_FOUND,                     "Query %1% not found");
ERRMSG(SCIDB_LE_QUERY_NOT_FOUND2,                    "Query already deallocated/cancelled");
ERRMSG(SCIDB_LE_QUERY_WAS_EXECUTED,                  "Query was executed previously");
ERRMSG(SCIDB_LE_MEMORY_ALLOCATION_ERROR,             "Error '%1%' during memory allocation");
ERRMSG(SCIDB_LE_REDISTRIBUTE_ERROR,                  "Attempt to redistribute on undefined partitioning schema");
ERRMSG(SCIDB_LE_QUERY_PARSING_ERROR,                 "Query parser failed with error '%1%'");
ERRMSG(SCIDB_LE_SUBQUERIES_NOT_SUPPORTED,           "Subqueries inside expressions not supported");
ERRMSG(SCIDB_LE_WRONG_ASTERISK_USAGE,               "Asterisk can be used only in aggregates");
ERRMSG(SCIDB_LE_ARRAY_NAME_REQUIRED,                "CREATE ARRAY statement requires array name");
ERRMSG(SCIDB_LE_ARRAY_ALREADY_EXIST,                "Array '%1%' already exists");
ERRMSG(SCIDB_LE_DUPLICATE_DIMENSION_NAME,           "Cannot create dimension '%1%'; name collides with existing object");
ERRMSG(SCIDB_LE_REFERENCE_NOT_ALLOWED_IN_DEFAULT,   "References not allowed in DEFAULT clause");
ERRMSG(SCIDB_LE_NULL_IN_NON_NULLABLE,               "Default value for non-nullable attribute '%1%' cannot be null");
ERRMSG(SCIDB_LE_COMPRESSOR_DOESNT_EXIST,            "Compressor with name '%1%' does not exist");
ERRMSG(SCIDB_LE_UNEXPECTED_OPERATOR_ARGUMENT,       "Operator '%1%' does not take an argument but was passed '%2%'");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT,     "Operator '%1%' expected %2% argument(s) but was passed %3%");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT2,    "Operator '%1%' expected more arguments");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT3,    "Operator '%1%' expected only %2% arguments");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENT,            "Expected '%1%' in position %2% of operator '%3%' but found '%4%'");
ERRMSG(SCIDB_LE_NESTED_ARRAYS_NOT_SUPPORTED,        "Nested arrays not supported");
ERRMSG(SCIDB_LE_NO_MAPPING_ARRAY,                   "There is no mapping array for dimensions '%1%' in array '%2%'");
ERRMSG(SCIDB_LE_AMBIGUOUS_OPERATOR_PARAMETER,       "Parameter of operator is ambiguous");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENT2,           "Parameter must be %1%");
ERRMSG(SCIDB_LE_AMBIGUOUS_ATTRIBUTE,                "Attribute '%1%' is ambiguous");
ERRMSG(SCIDB_LE_AMBIGUOUS_DIMENSION,                "Dimension '%1%' is ambiguous");
ERRMSG(SCIDB_LE_UNEXPECTED_OPERATOR_IN_EXPRESSION,  "Array operators cannot be used inside scalar expressions");
ERRMSG(SCIDB_LE_WRONG_AGGREGATE_ARGUMENTS_COUNT,    "An aggregate call must have exactly one argument");
ERRMSG(SCIDB_LE_WRONG_AGGREGATE_ARGUMENT,           "An aggregate call must contain a single attribute reference, SELECT statement or *");
ERRMSG(SCIDB_LE_REFERENCE_EXPECTED,                 "Attribute or dimension reference expected");
ERRMSG(SCIDB_LE_SORTING_QUIRK_WRONG_USAGE,          "Parser error: incorrect usage of SORT qualifier");
ERRMSG(SCIDB_LE_AGGREGATE_EXPECTED,                 "SELECT list items must contain a single aggregate if FROM is omitted");
ERRMSG(SCIDB_LE_WRONG_AGGREGATE_ARGUMENT2,          "An aggregate call must contain a single attribute reference or SELECT statement");
ERRMSG(SCIDB_LE_SINGLE_ATTRIBUTE_IN_INPUT_EXPECTED, "Input must have one attribute for aggregating in this form");
ERRMSG(SCIDB_LE_UNKNOWN_ATTRIBUTE_OR_DIMENSION,     "Attribute or dimension reference '%1%' does not exists");
ERRMSG(SCIDB_LE_AMBIGUOUS_ATTRIBUTE_OR_DIMENSION,   "Attribute or dimension reference '%1%' is ambiguous");
ERRMSG(SCIDB_LE_INPUT_EXPECTED,                     "Array name, array operator or SELECT statement expected");
ERRMSG(SCIDB_LE_CAN_NOT_STORE,                      "Cannot STORE or REDIMENSION_STORE output array into '%1%'. Schemas do not conform.");
ERRMSG(SCIDB_LE_AGGREGATE_CANT_BE_NESTED,           "Aggregate calls cannot be nested");
ERRMSG(SCIDB_LE_UNEXPECTED_SELECT_INSIDE_AGGREGATE, "SELECT inside aggregate not implemented");
ERRMSG(SCIDB_LE_ITEM_MUST_BE_INSIDE_AGGREGATE,      "SELECT item must be inside aggregate function");
ERRMSG(SCIDB_LE_ITEM_MUST_BE_INSIDE_AGGREGATE2,     "SELECT item must be constant or be inside aggregate function");
ERRMSG(SCIDB_LE_WRONG_REGRID_REDIMENSION_SIZES_COUNT,"REGRID and WINDOW clause must contain sizes for each dimension");
ERRMSG(SCIDB_LE_INJECTED_ERROR,                     "Injected error");
ERRMSG(SCIDB_LE_ERRNS_CAN_NOT_BE_UNREGISTERED,      "Error namespace '%1%' cannot be unregistered");
ERRMSG(SCIDB_LE_STORAGE_CLOSE_FAILED,               "Storage closed with errors");
ERRMSG(SCIDB_LE_UNKNOWN_MESSAGE_TYPE,               "Unknown/unexpected message type '%1%'");
ERRMSG(SCIDB_LE_IQUERY_PARSER_ERROR,                "Iquery parser error: '%1%'");
ERRMSG(SCIDB_LE_STORAGE_ALREADY_REGISTERED,         "Instance #%1% already registered in system catalog");
ERRMSG(SCIDB_LE_STORAGE_NOT_REGISTERED,             "Storage is not registered in system catalog");
ERRMSG(SCIDB_LE_CANT_ACCEPT_CONNECTION,             "Error #%1% (%2%) when accepting connection");
ERRMSG(SCIDB_LE_UNKNOWN_MESSAGE_TYPE2,              "Invalid message type for ID");
ERRMSG(SCIDB_LE_INVALID_SHEDULER_WORK_ITEM,         "Invalid work item for Scheduler");
ERRMSG(SCIDB_LE_INVALID_SHEDULER_PERIOD,            "Invalid period for Scheduler");
ERRMSG(SCIDB_LE_CONNECTION_ERROR2,                  "Connection error while sending");
ERRMSG(SCIDB_LE_CANT_OPEN_PATH,                     "Cannot open path '%1%'");
ERRMSG(SCIDB_LE_WRONG_ATTRIBUTE_TYPE,               "Attribute '%1%' has incorrect datatype (source: %2%, destination: %3%)");
ERRMSG(SCIDB_LE_WRONG_ATTRIBUTE_FLAGS,              "Attribute '%1%' has incorrect properties");
ERRMSG(SCIDB_LE_WRONG_SOURCE_ATTRIBUTE_TYPE,        "Source attribute '%1%' must be of type '%2%'");
ERRMSG(SCIDB_LE_WRONG_DESTINATION_ATTRIBUTE_TYPE,   "Destination attribute '%1%' must be of type '%2%'");
ERRMSG(SCIDB_LE_WRONG_DESTINATION_ATTRIBUTE_FLAGS,  "Destination attribute '%1%' must not have special properties");
ERRMSG(SCIDB_LE_DIMENSIONS_DONT_MATCH,              "Dimensions '%1%' and '%2%' do not match");
ERRMSG(SCIDB_LE_UNEXPECTED_DESTINATION_DIMENSION,   "No data provided for destination dimension '%1%'");
ERRMSG(SCIDB_LE_UNEXPECTED_DESTINATION_ATTRIBUTE,   "No data provided for destination attribute '%1%'");
ERRMSG(SCIDB_LE_AGGREGATE_RESULT_CANT_BE_TRANSFORMED_TO_DIMENSION,"Aggregate result '%1%' cannot be transformed into a dimension");
ERRMSG(SCIDB_LE_CHUNK_WRONG_ITERATION_MODE,         "Operator does not support the requested chunk iteration mode");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR1,                  "The substitute array '%1%' must have only one dimension");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR2,                  "The substitute array '%1%' must have only one attribute");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR4,                  "The dimension must start at 0");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR5,                  "Input attribute '%1%' does not match the datatype of '%2%'");
ERRMSG(SCIDB_LE_LOGICAL_JOIN_ERROR1,                "Join must be applied to arrays of same dimensionality");
ERRMSG(SCIDB_LE_LOGICAL_JOIN_ERROR2,                "Joined arrays have different schemas");
ERRMSG(SCIDB_LE_LIST_ERROR1,                        "Parameter of 'list' operator can be 'aggregates', 'arrays', 'operators', 'types', 'functions', 'queries', 'libraries', 'instances'");
ERRMSG(SCIDB_LE_CANT_CREATE_DIRECTORY,              "Cannot create directory '%1%'");
ERRMSG(SCIDB_LE_EXPLAIN_ERROR1,                     "Operator 'explain_physical' accepts 1 or 2 parameters only");
ERRMSG(SCIDB_LE_EXPLAIN_ERROR2,                     "Second parameter of 'explain_logical' operator must be 'aql' or 'afl'");
ERRMSG(SCIDB_LE_OPERATION_NOT_FOUND,                "Operation '%1%' not defined for type '%2%'");
ERRMSG(SCIDB_LE_NO_MAPPING_FOR_COORDINATE,          "No mapping for such coordinate value");
ERRMSG(SCIDB_LE_UNDEFINED_DISTRIBUTION_CANT_HAVE_MAPPER,"An undefined distribution cannot have a mapper");
ERRMSG(SCIDB_LE_SPECIFIC_DISTRIBUTION_REQUIRED,     "The chunk distribution requirement 'SpecifyAnyOrder' does not match what is provided");
ERRMSG(SCIDB_LE_CANT_GET_SYSTEM_TIME,               "Cannot get system time");
ERRMSG(SCIDB_LE_TIMER_RETURNED_UNEXPECTED_ERROR,    "Timer (expires_from_now) returned unexpected error '%1%'");
ERRMSG(SCIDB_LE_TIMER_RETURNED_UNEXPECTED_ERROR2,   "Timer handler returned unexpected error '%1%'");
ERRMSG(SCIDB_LE_CANT_LINK_DATA_TO_ZERO_BUFFER,      "Cannot link data to zero length buffer");
ERRMSG(SCIDB_LE_CANT_MODIFY_VALUE_WITH_LINKED_DATA, "Cannot modify value object with linked data");
ERRMSG(SCIDB_LE_CANT_SET_VALUE_VECTOR_TO_DEFAULT,   "Cannot set value vector to default");
ERRMSG(SCIDB_LE_CANT_ADD_NULL_FACTORY,              "Cannot add NULL factory to Aggregate Library");
ERRMSG(SCIDB_LE_DUPLICATE_AGGREGATE_FACTORY,        "Cannot add duplicate factory to Aggregate Library");
ERRMSG(SCIDB_LE_CANT_INCREMENT_LOCK,                "Cannot increment lock counter for '%1%' because query was cancelled");
ERRMSG(SCIDB_LE_DIMENSIONS_MISMATCH,                "Dimension mismatch");
ERRMSG(SCIDB_LE_CHUNK_ALREADY_EXISTS,               "An existing chunk cannot be updated");
ERRMSG(SCIDB_LE_CANT_MERGE_CHUNKS_WITH_VARYING_SIZE,"Merge of chunks with varying size attribute type is not supported");
ERRMSG(SCIDB_LE_CANT_UPDATE_READ_ONLY_CHUNK,        "Chunk is read-only and cannot be updated");
ERRMSG(SCIDB_LE_TYPE_MISMATCH_BETWEEN_AGGREGATE_AND_CHUNK,"Type mismatch between aggregate and chunk");
ERRMSG(SCIDB_LE_AGGREGATE_STATE_MUST_BE_NULLABLE,   "Aggregate NULL flag must be TRUE");
ERRMSG(SCIDB_LE_EXTRACT_EXPECTED_FIXED_SIZE_ATTRIBUTE,"extractData expects fixed-size attribute");
ERRMSG(SCIDB_LE_EXTRACT_UNEXPECTED_BOOLEAN_ATTRIBUTE,"extractData does not expect a boolean attribute");
ERRMSG(SCIDB_LE_WRONG_NUMBER_OF_DIMENSIONS,         "Wrong number of dimensions");
ERRMSG(SCIDB_LE_UNALIGNED_COORDINATES,              "Coordinates should be aligned on chunk boundary");
ERRMSG(SCIDB_LE_CANT_ALLOCATE_MEMORY,               "Failed to allocate memory");
ERRMSG(SCIDB_LE_NO_CURRENT_CHUNK,                   "No current chunk");
ERRMSG(SCIDB_LE_CHUNK_OUT_OF_BOUNDARIES,            "Chunk is outside of array boundaries");
ERRMSG(SCIDB_LE_ACCESS_TO_EMPTY_CELL,               "Access to empty cell");
ERRMSG(SCIDB_LE_ASSIGNING_NULL_TO_NON_NULLABLE,     "Assigning NULL to non-nullable attribute");
ERRMSG(SCIDB_LE_TILE_NOT_ALIGNED,                   "Tile position is not correctly aligned");
ERRMSG(SCIDB_LE_TILE_MODE_EXPECTED_STRIDE_MAJOR_ORDER,"Tiles can only be written in stride major order");
ERRMSG(SCIDB_LE_INVALID_OPERATION_FOR_SEQUENTIAL_MODE,"Invalid operation for sequential mode");
ERRMSG(SCIDB_LE_CANT_UPDATE_BITMAP_IN_TILE_MODE,    "Cannot update bitmap in tile mode");
ERRMSG(SCIDB_LE_NO_ASSOCIATED_BITMAP_CHUNK,         "No associated bitmap chunk");
ERRMSG(SCIDB_LE_NO_CURRENT_BITMAP_CHUNK,            "No current bitmap chunk");
ERRMSG(SCIDB_LE_CANT_FETCH_CHUNK_BODY,              "Failed to fetch chunk body");
ERRMSG(SCIDB_LE_MULTIDIMENSIONAL_ARRAY_NOT_ALLOWED, "Multidimensional array is not allowed");
ERRMSG(SCIDB_LE_OP_SAMPLE_ERROR1,                     "Seed should be a positive integer");
ERRMSG(SCIDB_LE_OP_SAMPLE_ERROR2,                     "Probability should be in interval  (0..1]");
ERRMSG(SCIDB_LE_INVALID_INSTANCE_ID,                    "Invalid instance ID: '%1%'");
ERRMSG(SCIDB_LE_ARRAYS_NOT_CONFORMANT,              "Arrays are not conformant");
ERRMSG(SCIDB_LE_OP_REDIMENSION_ERROR1,              "Destination array for REDIMENSION must have EMPTY flag TRUE");
ERRMSG(SCIDB_LE_NO_MEMORY_TO_ALLOCATE_MATRIX,       "Not enough memory to allocate matrix");
ERRMSG(SCIDB_LE_NO_MEMORY_TO_ALLOCATE_VECTOR,       "Not enough memory to allocate vector");
ERRMSG(SCIDB_LE_CANT_UPDATE_CHUNK,                  "Cannot update disk chunk");
ERRMSG(SCIDB_LE_INVALID_REDUNDANCY,                 "Redundancy should be smaller than number of instances");
ERRMSG(SCIDB_LE_INSTANCE_OFFLINE,                       "Instance #%1% is offline");
ERRMSG(SCIDB_LE_DIVISION_BY_ZERO,                   "Division by zero");
ERRMSG(SCIDB_LE_FAILED_PARSE_STRING,                "Failed to parse string");
ERRMSG(SCIDB_LE_DIMENSION_EXPECTED,                 "Dimension has to be specified");
ERRMSG(SCIDB_LE_REDISTRIBUTE_AGGREGATE_ERROR1,      "Empty tag attribute should be last and cannot be aggregated");
ERRMSG(SCIDB_LE_REDISTRIBUTE_ERROR1,                "Empty tag attribute should be last");
ERRMSG(SCIDB_LE_CANT_MERGE_READONLY_CHUNK,          "Cannot merge read-only chunk");
ERRMSG(SCIDB_LE_INVALID_SPECIFIED_DATE,             "Specified date is not valid");
ERRMSG(SCIDB_LE_CANT_CONVERT_NULL,                  "Cannot convert NULL value");
ERRMSG(SCIDB_LE_NO_QUORUM2,                         "Not enough online instances to execute query");
ERRMSG(SCIDB_LE_OP_REGRID_ERROR1,                   "Regrid interval should be positive");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR2,                   "Window doesn't fit in overlap area");
ERRMSG(SCIDB_LE_OP_BUILD_ERROR1,                    "Build expression should not access attributes");
ERRMSG(SCIDB_LE_OP_BUILD_ERROR2,                    "Constructed array should have one attribute");
ERRMSG(SCIDB_LE_OP_BUILD_ERROR3,                    "Array with open boundary cannot be built");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR1,             "Build_sparse expression should not access attributes");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR2,             "Build_sparse predicate should not access attributes");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR3,             "Constructed array should have one attribute");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR4,             "Cannot BUILD array with open boundary");
ERRMSG(SCIDB_LE_OP_CAST_ERROR1,                     "Mismatched number of attributes");
ERRMSG(SCIDB_LE_OP_CAST_ERROR3,                     "Attribute '%1%' flags doesn't match");
ERRMSG(SCIDB_LE_OP_CAST_ERROR4,                     "Mismatched number of dimensions");
ERRMSG(SCIDB_LE_OP_CAST_ERROR5,                     "Dimension '%1%' length doesn't match");
ERRMSG(SCIDB_LE_OP_CONCAT_ERROR1,                   "Arrays with open boundary cannot be concatenated");
ERRMSG(SCIDB_LE_OP_CROSSJOIN_ERROR1,                "Dimension should be specified only once in JOIN ON list");
ERRMSG(SCIDB_LE_OP_DELDIM_ERROR1,                   "Cannot delete the only dimension of array");
ERRMSG(SCIDB_LE_OP_DELDIM_ERROR2,                   "Only dimension with length 1 can be removed");
ERRMSG(SCIDB_LE_OP_REDIMENSION_ERROR2,              "The result of an aggregate cannot be transformed into a dimension");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR1,        "Resulting array has no dimensions");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR2,        "Destination array for REDIMENSION should have EMPTY flag TRUE");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR5,        "Attribute '%1%' cannot be transformed into a dimension");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR1,                    "Out-of-sequence chunk in input file");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR2,                    "Input parser expected '%1%'");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR3,                    "Input parser expected coordinate");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR4,                    "Invalid chunk position");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR5,                    "Duplicate chunk address");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR6,                    "Too much nesting");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR7,                    "Out of bounds");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR8,                    "Input parser expected literal");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR9,                    "No values for empty cells should be defined: only () is accepted");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR10,                   "This version of scidb does not support this input file");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR11,                   "Chunk is out of window boundary");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR13,                   "Unterminated string literal");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR14,                   "Bad literal");
ERRMSG(SCIDB_LE_NO_CURRENT_POSITION,                "No current position");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR2,                 "Matrix must have 1 attribute");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR3,                 "Both input arrays to multiply must be 2-dimensional");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR4,                 "Cannot multiply unbounded matrices");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR5,                 "Matrix dimensions must match");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR6,                 "Matrix chunk sizes in the joint dimension must match");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR7,                 "Matrices to be multiplied should have the same attribute type");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR8,                 "Matrices with nullable attributes cannot be multiplied");
ERRMSG(SCIDB_LE_OP_NORMALIZE_ERROR1,                "Vector must contain 1 attribute");
ERRMSG(SCIDB_LE_OP_NORMALIZE_ERROR2,                "Array must be 1-D vector");
ERRMSG(SCIDB_LE_OP_REPART_ERROR1,                   "Mismatched number of dimensions");
ERRMSG(SCIDB_LE_OP_REPART_ERROR3,                   "Mismatched array base");
ERRMSG(SCIDB_LE_OP_REPART_ERROR4,                   "Mismatched array length");
ERRMSG(SCIDB_LE_OP_REPART_ERROR5,                   "Array should have fixed lower boundary");
ERRMSG(SCIDB_LE_OP_RESHAPE_ERROR2,                  "Chunk should have no overlap");
ERRMSG(SCIDB_LE_OP_RESHAPE_ERROR3,                  "Incompatible array dimensions");
ERRMSG(SCIDB_LE_OP_REVERSE_ERROR1,                  "Only fixed-size array can be reversed");
ERRMSG(SCIDB_LE_OP_SLICE_ERROR1,                    "Input array has too few dimensions for slice");
ERRMSG(SCIDB_LE_OP_SLICE_ERROR2,                    "Slice coordinate is out of bounds");
ERRMSG(SCIDB_LE_OP_SORT_ERROR2,                     "Column index is out of range");
ERRMSG(SCIDB_LE_OP_SORT_ERROR3,                     "Cannot jump more than one chunk forward");
ERRMSG(SCIDB_LE_OP_SORT_ERROR4,                     "Chunk out of window");
ERRMSG(SCIDB_LE_OP_THIN_ERROR1,                     "Step must be divider of chunk size");
ERRMSG(SCIDB_LE_OP_THIN_ERROR2,                     "Starting position is out of bounds");
ERRMSG(SCIDB_LE_OP_THIN_ERROR3,                     "Starting offset must be smaller than step");
ERRMSG(SCIDB_LE_OP_THIN_ERROR4,                     "Step must be smaller than chunk size");
ERRMSG(SCIDB_LE_OP_THIN_ERROR5,                     "Step must be positive number");
ERRMSG(SCIDB_LE_OP_XGRID_ERROR1,                    "Cannot use xgrid on an unbounded array");
ERRMSG(SCIDB_LE_OP_XGRID_ERROR2,                    "Xgrid arguments must be positive");
ERRMSG(SCIDB_LE_DIMENSION_START_CANT_BE_UNBOUNDED,  "Dimension start cannot be unbounded");
ERRMSG(SCIDB_LE_HIGH_SHOULDNT_BE_LESS_LOW,          "Upper boundary of dimension must be greater than lower boundary");
ERRMSG(SCIDB_LE_OVERLAP_CANT_BE_LARGER_CHUNK,       "Chunk overlap cannot be larger than chunk size");
ERRMSG(SCIDB_LE_PIN_UNPIN_DISBALANCE,               "pin/unpin unbalanced, or race condition during close");
ERRMSG(SCIDB_LE_COMPRESS_METHOD_NOT_DEFINED,        "Compression method is not defined for the chunk");
ERRMSG(SCIDB_LE_STORAGE_DESCRIPTOR_INVALID_FORMAT,  "Invalid format of storage description file");
ERRMSG(SCIDB_LE_CHUNK_NOT_FOUND,                    "Chunk not found");
ERRMSG(SCIDB_LE_NO_FREE_SPACE,                      "No more free space");
ERRMSG(SCIDB_LE_CHUNK_SIZE_TOO_LARGE,               "Chunk size %1% is larger than segment size %2%");
ERRMSG(SCIDB_LE_CANT_REALLOCATE_MEMORY,             "Failed to reallocate memory");
ERRMSG(SCIDB_LE_INVALID_LIVENESS,                   "Invalid liveness");
ERRMSG(SCIDB_LE_LIVENESS_MISMATCH,                  "Liveness mismatch");
ERRMSG(SCIDB_LE_MESSAGE_MISSED_QUERY_ID,            "Message has no query ID");
ERRMSG(SCIDB_LE_MISMATCHED_COORDINATES_IN_PHYSICAL_BOUNDARIES,"Mismatched coordinates in physical boundaries");
ERRMSG(SCIDB_LE_MISMATCHED_BOUNDARIES,              "Mismatched boundaries");
ERRMSG(SCIDB_LE_CANT_CREATE_BOUNDARIES_FROM_INFINITE_ARRAY,"Cannot create boundaries from infinite array");
ERRMSG(SCIDB_LE_LIVENESS_EMPTY,                     "Liveness unexpectedly contains no data");
ERRMSG(SCIDB_LE_DUPLICATE_QUERY_ID,                 "Query with same ID already exists in the system");
ERRMSG(SCIDB_LE_CANT_GENERATE_UTC_TIME,             "Unable to generate UTC time");
ERRMSG(SCIDB_LE_CANT_CREATE_SG_WITH_UNDEFINED_DISTRIBUTION,"Cannot create an SG with undefined distribution");
ERRMSG(SCIDB_LE_CANT_LOCK_DATABASE,                 "Failed to get exclusive access to the database");
ERRMSG(SCIDB_LE_DATABASE_HEADER_CORRUPTED,          "Database header has been corrupted");
ERRMSG(SCIDB_LE_CANT_DECOMPRESS_CHUNK,              "Failed to decompress chunk");
ERRMSG(SCIDB_LE_CHUNK_NOT_PINNED,                   "Accessed chunk should be pinned");
ERRMSG(SCIDB_LE_INVALID_MONTH_REPRESENTATION,       "Invalid month representation: %1%");
ERRMSG(SCIDB_LE_INVALID_USER_ERROR_CODE,            "Cannot register error namespace '%1%' with error code '%2%': user-defined error codes must be greater than %3%. Use constant SCIDB_USER_ERROR_CODE_START to define your first error code.");
ERRMSG(SCIDB_LE_ATTRIBUTES_MISMATCH,                "Attributes mismatch");
ERRMSG(SCIDB_LE_INVALID_FUNCTION_ARGUMENT,          "Invalid function argument: %1%");
ERRMSG(SCIDB_LE_LOGICAL_CHUNK_SIZE_TOO_LARGE,       "Chunk size should not exceed 2^63");
ERRMSG(SCIDB_W_FILE_NOT_FOUND_ON_INSTANCES,         "File '%1%' not found on instance(s) %2%");
ERRMSG(SCIDB_LE_FILE_IMPORT_FAILED,                 "Import from file '%1%' (instance %2%) to array '%3%' failed at line %4%, column %5%, offset %6%, value='%7%': %8%");
ERRMSG(SCIDB_LE_ACCESS_TO_RAW_CHUNK,                "Access to raw chunk of array '%3%'");
ERRMSG(SCIDB_LE_INVALID_COMMIT_STATE,              "'%2%' request for query (%1%) is invalid in the current state");
ERRMSG(SCIDB_LE_WRONG_ASTERISK_USAGE2,              "Asterisk for all array versions access can be used only in SELECT");
ERRMSG(SCIDB_LE_LE_CANT_ACCESS_INDEX_FOR_ALLVERSIONS,"Only index of specified array version can be accessed");
ERRMSG(SCIDB_LE_CANT_ACCESS_ARRAY_VERSION,          "Array version inaccessible in this context");
ERRMSG(SCIDB_LE_CANT_ACCESS_INDEX_ARRAY,            "Index array inaccessible in this context");
ERRMSG(SCIDB_LE_CANT_UNLOAD_MODULE,                 "Cannot unload module '%1%'. The module is not loaded");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR6,        "Aggregate '%1%' doesn't match with any attribute");
ERRMSG(SCIDB_LE_SUBSTITUTE_FAILED,                  "Failed to substitute missing reason '%1%'");
ERRMSG(SCIDB_LE_TRUNCATION,                         "Varying size type with length %1% cannot be converted to fixed size type with limit %2%");
ERRMSG(SCIDB_LE_LOOKUP_BAD_PARAM,                   "Number of attributes in pattern array of LOOKUP should match number of dimensions in source array");
ERRMSG(SCIDB_LE_INVALID_STORAGE_HEADER,             "This version of SciDB cannot read this storage file (header magic mismatch)");
ERRMSG(SCIDB_LE_MISMATCHED_STORAGE_FORMAT_VERSION,  "This version of SciDB cannot read this storage file (file min %1%, file max %2%, system %3%)");
ERRMSG(SCIDB_LE_OP_CROSSJOIN_ERROR2,                "Joined dimensions should be specified for both arrays");
ERRMSG(SCIDB_LE_OP_NORMALIZE_ERROR3,                "Attribute must be of double type");
ERRMSG(SCIDB_LE_EXPLICIT_EMPTY_FLAG_NOT_ALLOWED,    "Explicit empty flag attribute not allowed. Use EMPTY keyword");
ERRMSG(SCIDB_LE_INCONSISTENT_ARRAY_DESC,            "Array descriptor is inconsistent");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR7,        "Too many duplicates for REDIMENSION_STORE with synthetic dimension: increase chunk size");
ERRMSG(SCIDB_LE_QUERY_ALREADY_COMMITED,              "Operation not possible because the query (%1%) has already been commited");
ERRMSG(SCIDB_LE_NETWORK_QUEUE_FULL,                  "Network queue is full");
ERRMSG(SCIDB_LE_INVALID_MESSAGE_FORMAT,             "Invalid message format for type %1%");
ERRMSG(SCIDB_LE_INVALID_ARRAY_LITERAL,              "Build required constant string when array literal flag is true");
ERRMSG(SCIDB_LE_INVALID_REDIMENSION_POSITION,       "Cannot redimension coordinates %1%; the position is not valid in the destination array");
ERRMSG(SCIDB_LE_SYSCALL_ERROR,                      "Invocation of %1% failed with return code=%2%, error=%3%, arg(s)=%4%");
ERRMSG(SCIDB_LE_NON_FQ_PATH_ERROR,                  "Path %1% is not fully qualified");
ERRMSG(SCIDB_LE_UNKNOWN_CTX,                        "Unknown/unexpected context type '%1%'");
ERRMSG(SCIDB_LE_CANT_LOCK_FILE,                     "Failed to get exclusive access to the file %1%, error = %2%");
ERRMSG(SCIDB_LE_TEMPLATE_PARSE_ERROR,               "Failed to parse template at position %1%");
ERRMSG(SCIDB_LE_TEMPLATE_FIXED_SIZE_TYPE,           "Length should not be explicitly specified for fixed size type %1%");
ERRMSG(SCIDB_LE_FILE_WRITE_ERROR,                   "Failed to write file: %1%");
ERRMSG(SCIDB_LE_FILE_READ_ERROR,                    "Failed to read file: %1%");
ERRMSG(SCIDB_LE_UNSUPPORTED_FORMAT,                 "Unsupported format: %1%");
ERRMSG(SCIDB_LE_MULTIPLE_DIMENSION_SPECIFICATION,   "Same dimension specified multiple times");
ERRMSG(SCIDB_LE_NOT_ENOUGH_DIMENSIONS_IN_SPECIFICATION,"Not all dimensions were specified");
ERRMSG(SCIDB_LE_PARTITION_NAME_NOT_UNIQUE,          "Partition name must be unique");
ERRMSG(SCIDB_LE_PARTITION_NAME_NOT_SPECIFIED,       "Partition name not specified");
ERRMSG(SCIDB_LE_UNKNOWN_PARTITION_NAME,             "Unknown partition name");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR3,                   "PRECEDING and FOLLOWING must be non-negative values");
ERRMSG(SCIDB_LE_WRONG_OVER_USAGE,                   "OVER keyword can only be applied to aggregates");
ERRMSG(SCIDB_W_MISSING_REASON_OUT_OF_BOUNDS,        "Missing reason cannot be imported in binary file");
ERRMSG(SCIDB_LE_DDL_CANT_BE_NESTED,                 "DDL operators cannot be nested");
ERRMSG(SCIDB_LE_NO_OPERATOR_RESULT,                 "Nested operator did not return any result to parent");
ERRMSG(SCIDB_LE_CATALOG_NEWER_THAN_SCIDB,           "Cannot connect SciDB with metadata version %1% to catalog with metadata version %2%");
ERRMSG(SCIDB_LE_DDL_SHOULDNT_HAVE_INPUTS,           "DDL operators cannot accept input arrays");
ERRMSG(SCIDB_LE_UNSUPPORTED_INPUT_ARRAY,            "Operator %1% does not support the given virtual input array. Consider splitting the query and using store() to create a temporary result");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR4,                   "Window size should be greater than 1");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR15,                   "Expected boolean constant for empty indicator");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR16,                   "Number of errors exceeds threshold");
ERRMSG(SCIDB_LE_CHUNK_SIZE_MUST_BE_POSITIVE,        "Chunk size must be positive");
ERRMSG(SCIDB_LE_OPERATION_FAILED_WITH_ERRNO,        "Operation %1% failed with errno %2%");
ERRMSG(SCIDB_LE_RESOURCE_BUSY,                      "Not enough resources: %1%");
ERRMSG(SCIDB_LE_NESTING_PROHIBITED,                 "Operator %1% can not be nested");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR5,                   "Algorithm must be one of %1%");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR6,                   "Using materialize op without materialized input");
ERRMSG(SCIDB_LE_CONSTANT_EXPRESSION_EXPECTED,       "Constant expression expected");
ERRMSG(SCIDB_LE_TYPE_EXPECTED,                      "Expected constant or expression with type '%1%'");
ERRMSG(SCIDB_LE_INCORRECT_CHUNK_SIZE,               "Chunk size must be between 1 and '%1%'");
ERRMSG(SCIDB_LE_INCORRECT_OVERLAP_SIZE,             "Overlap length must be between 0 and %1%");
ERRMSG(SCIDB_LE_INCORRECT_DIMENSION_BOUNDARY,       "Dimension boundaries must be between '%1%' and '%2%'");
ERRMSG(SCIDB_LE_WRONG_LANGUAGE_STRING,              "Language string should be AQL or AFL");
ERRMSG(SCIDB_LE_BAD_SINGLE_ATTRIBUTE_ARRAY,         "Operator '%1%' requires a %3% valued array as argument %2%");
ERRMSG(SCIDB_LE_BAD_ARRAY_DIMENSIONS,               "Operator '%1%' requires a %3% dimensional array as argument %2%");
ERRMSG(SCIDB_LE_BAD_VECTOR_LENGTH,                  "Operator '%1%' requires a vector of length at least %3% as argument %2%");
ERRMSG(SCIDB_LE_OP_CAST_ERROR10,                    "Cannot cast attribute '%1%' type from '%2%' to '%3%'");
ERRMSG(SCIDB_LE_CANNOT_RECOVER_RESTARTABLE_WORK,    "Cannot recover restartable work");
ERRMSG(SCIDB_LE_CANNOT_MODIFY_ENVIRONMENT,          "Internal error, could not modify environ.");
ERRMSG(SCIDB_LE_MISMATCHED_OPAQUE_FORMAT_VERSION,   "This version of SciDB cannot read this opaque file (file version %1%, system version %2%)");
ERRMSG(SCIDB_LE_CANNOT_ADD_AGGREGATE,               "Can not add aggregate '%1%'. Scalar function with same signature already exists");
ERRMSG(SCIDB_LE_CANNOT_ADD_FUNCTION,                "Can not add function '%1%'. Aggregate with same signature already exists");
ERRMSG(SCIDB_LE_QUERY_TOO_BIG,                      "Query is too big. Query size: %1% bytes. Max allowed size: %2% bytes");
ERRMSG(SCIDB_LE_TOO_MANY_OPEN_FILES,                "Reached per-process fd limit");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR9,                 "Non-supported attribute type in sparse multiply");
ERRMSG(SCIDB_LE_CUMULATE_NEEDS_AGGREGATES,          "Operator 'cumulate' requires one input array and at least one aggregate call");
ERRMSG(SCIDB_LE_CUMULATE_NO_OVERLAP,                "For now, cumulate does not handle dimensions with overlaps");
ERRMSG(SCIDB_LE_CUMULATE_DIM_AFTER_AGGREGATES,      "Operator 'cumulate' requires that the dimension parameter, if exists, should be the last one");
ERRMSG(SCIDB_LE_ARENA_OVERFLOWED,                   "A request to allocate memory caused an arithmetic overflow.\n   arena: %1%");
ERRMSG(SCIDB_LE_ARENA_EXHAUSTED,                    "An attempt was made to allocate more memory than is available.\n   arena  : %1%\n   request: %2%");
ERRMSG(SCIDB_LE_UNIQ_SINGLE_ATTRIBUTE_ONLY,         "The input to operator 'uniq' must have only one attribute");
ERRMSG(SCIDB_LE_UNIQ_SINGLE_DIMENSION_AT_ZERO,      "The input to operator 'uniq' must have a single dimension that starts at 0");
ERRMSG(SCIDB_LE_CANNOT_PARSE_INTEGER_PARAMETER,     "The parameter '%1%' could not be parsed into an integer value");
ERRMSG(SCIDB_LE_PARAMETER_NOT_POSITIVE_INTEGER,     "The parameter '%1%' is not valid; must be a positive integer");
ERRMSG(SCIDB_LE_UNRECOGNIZED_PARAMETER,             "Unrecognized parameter '%1%'");
ERRMSG(SCIDB_LE_CANNOT_BE_SET_MORE_THAN_ONCE,       "The '%1%' parameter cannot be set more than once");
ERRMSG(SCIDB_LE_IMPROPER_INDEX_SHAPE,               "The index array must have only one attribute and one dimension");
ERRMSG(SCIDB_LE_NOT_AN_ATTRIBUTE_IN_INPUT,          "%1% is not an attribute in the input array");
ERRMSG(SCIDB_LE_ATTRIBUTES_DO_NOT_MATCH_TYPES,      "The type of attribute %1% (%2%) does not match the type of %3% (%4%)");
ERRMSG(SCIDB_LE_ATTRIBUTE_CANNOT_BE_NULLABLE,       "The index attribute %1% cannot be nullable");
ERRMSG(SCIDB_LE_CANNOT_PARSE_BOOLEAN_PARAMETER,     "The parameter '%1%' could not be parsed into a boolean");
ERRMSG(SCIDB_LE_CHUNK_SEGMENT_SIZE_INCOMPATIBLE,    "Configured chunk segment size: %1% bytes, doesn't match stored chunk segment size: %2% bytes");
ERRMSG(SCIDB_LE_CHUNK_SEGMENT_SIZE_ILLEGAL,         "Cannot initialize database with chunk segment size of %1% bytes");
ERRMSG(SCIDB_LE_BAD_BLOCK_COMMENT,                  "The block '/*' comment is not terminated with a matching '*/'");
ERRMSG(SCIDB_LE_BAD_LITERAL_REAL,                   "'%1%' is too large to represent as a double");
ERRMSG(SCIDB_LE_BAD_LITERAL_INTEGER,                "'%1%' is too large to represent as an integer");
ERRMSG(SCIDB_LE_NAME_REDEFINED,                     "'%1%' has already been defined");
ERRMSG(SCIDB_LE_NAME_NOT_APPLICABLE,                "'%1%' is not an entity that can be applied (such as an operator or function)");
ERRMSG(SCIDB_LE_NAME_IS_RECURSIVE,                  "'%1%' is defined recursively (recursion not yet supported)");
ERRMSG(SCIDB_LE_NAME_ARITY_MISMATCH,                "'%1%' is applied to the wrong number of arguments");
ERRMSG(SCIDB_LE_DATASTORE_GUID_NOT_UNIQUE,          "Attempt to create a DataStore on file '%1%' with non-unique guid '%2%'");
ERRMSG(SCIDB_LE_STORAGE_FILE_INVALID_FORMAT,        "The storage file '%1%' has an invalid format");
ERRMSG(SCIDB_LE_DATASTORE_NOT_FOUND,                "Attempt to access non-existent DataStore with guid '%1%'");
ERRMSG(SCIDB_LE_DATASTORE_CHUNK_CORRUPTED,          "Chunk header corrupted in DataStore with guid '%1%' offset '%2%'");
ERRMSG(SCIDB_LE_DATASTORE_CORRUPT_FREELIST,         "Stored freelist for data store corrupted: '%1%'");

//Next ERRMSG

ERRMSG(SCIDB_LE_PG_QUERY_EXECUTION_FAILED,          "Execution of query '%1%' failed with error %2%");
ERRMSG(SCIDB_LE_LIBPQ_NOT_THREADSAFE,               "libpq is not threadsafe. Rebuild it with option --enable-thread-safety");
ERRMSG(SCIDB_LE_CANT_CONNECT_PG,                    "Cannot connect to PostgreSQL catalog: '%1%'");
ERRMSG(SCIDB_LE_UNREACHABLE_CODE,                   "Fatal: Unreachable code is reached in '%1%'");
ERRMSG(SCIDB_LE_UNITTEST_FAILED,                    "Unit test failed! Test = '%1%', failure = '%2%'");
ERRMSG(SCIDB_LE_NEED_UPGRADE_CONFIRMATION,          "In order to proceed, the 'enable-catalog-upgrade' setting must be enabled");

// Copied from P4
ERRMSG(SCIDB_LE_DLA_ERROR13,                        "Request for unknown attribute");
ERRMSG(SCIDB_LE_DLA_ERROR14,                        "Specified attribute not found in array");
ERRMSG(SCIDB_LE_DLA_ERROR15,                        "Ranked attribute cannot be an empty indicator");
ERRMSG(SCIDB_LE_DLA_ERROR16,                        "Specified dimension not found in array");
ERRMSG(SCIDB_LE_DLA_ERROR17,                        "The number of samples passed to quantile must be at least 1");
