/*
**
* BEGIN_COPYRIGHT
*
* This file is part of SciDB.
* Copyright (C) 2008-2012 SciDB, Inc.
*
* SciDB is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation version 3 of the License.
*
* SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
* INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
* NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
* the GNU General Public License for the complete license terms.
*
* You should have received a copy of the GNU General Public License
* along with SciDB.  If not, see <http://www.gnu.org/licenses/>.
*
* END_COPYRIGHT
*/

ERRMSG(SCIDB_E_NO_ERROR,                             "No errors");

ERRMSG(SCIDB_LE_UNKNOWN_ERROR,                       "Unknown error: %1%");

ERRMSG(SCIDB_LE_ERRNS_ALREADY_REGISTERED,            "Error namespace '%1%' already registered");
ERRMSG(SCIDB_LE_ERRNS_CANT_BE_REGISTERED,            "Error namespace '%1%' cannot be unregistered");

ERRMSG(SCIDB_LE_AGGREGATE_NOT_FOUND,                 "Aggregate name '%1%' is not registered in the system");
ERRMSG(SCIDB_LE_AGGREGATE_DOESNT_SUPPORT_ASTERISK,   "Aggregate '%1%' does not support asterisk");
ERRMSG(SCIDB_LE_AGGREGATE_DOESNT_SUPPORT_TYPE,       "Aggregate '%1%' does not support input type '%2%'");
ERRMSG(SCIDB_LE_UNHANDLED_VAR_PARAMETER,             "Operator '%1%' cannot handle variable number of parameters");
ERRMSG(SCIDB_LE_NO_MEMORY_FOR_VALUE,                 "No memory for new value");
ERRMSG(SCIDB_LE_THREAD_EVENT_ERROR,                  "Error state '%1%' detected in event wait");
ERRMSG(SCIDB_LE_THREAD_SEMAPHORE_ERROR,              "Error state '%1%' detected in semaphore enter");
ERRMSG(SCIDB_LE_CANT_LOAD_MODULE,                    "Cannot load module '%1%', dlopen returned '%2%");
ERRMSG(SCIDB_LE_TOO_NEW_MODULE,                      "This plugin is not supported by this version of SciDB. The plugin is version %1% is %2%.%3%.%4%.%5% but but SciDB version is %6%");
ERRMSG(SCIDB_LE_CANT_FIND_SYMBOL,                    "Cannot find symbol '%1%', dlsym returned '%2%'");
ERRMSG(SCIDB_LE_INPUTS_MUST_BE_BEFORE_PARAMS,        "Error in operator '%1%'. All inputs must be before other parameters");
ERRMSG(SCIDB_LE_VAR_MUST_BE_AFTER_PARAMS,            "Error in operator '%1%'. Variadic parameters must appear last");
ERRMSG(SCIDB_LE_UNEXPECTED_GETREPARTSCHEMA,          "Unexpected getRepartSchema that is not overwritten");
ERRMSG(SCIDB_LE_PWRITE_ERROR,                        "pwrite failed to write %1% byte(s) to the position %2% with error %3%");
ERRMSG(SCIDB_LE_PREAD_ERROR,                         "pread failed to read %1% byte(s) from position %2% with error %3%");
ERRMSG(SCIDB_LE_OPERATOR_NOT_FOUND,                  "Operator '%1%' not found");
ERRMSG(SCIDB_LE_ARRAY_DOESNT_EXIST,                  "Array '%1%' does not exist");
ERRMSG(SCIDB_LE_ARRAYID_DOESNT_EXIST,                "Array with id '%1%' does not exist");
ERRMSG(SCIDB_LE_CANT_OPEN_FILE,                      "Cannot open file '%1%' errno %2%");
ERRMSG(SCIDB_LE_INSTANCE_DOESNT_EXIST,                   "Instance with id %1% does not exist");
ERRMSG(SCIDB_LE_ATTRIBUTE_DOESNT_EXIST,              "Attribute with id %1% does not exist in array '%2%'");
ERRMSG(SCIDB_LE_DUPLICATE_ATTRIBUTE_NAME,            "Cannot create attribute '%1%'; name collides with existing object");
ERRMSG(SCIDB_LE_ILLEGAL_OPERATION,                   "Illegal operation: %1%");
ERRMSG(SCIDB_LE_UNKNOWN_OPERATION,                   "Operation '%1%' for type '%2%' not found");
ERRMSG(SCIDB_LE_WORK_QUEUE_FULL,                     "Work queue is full");
ERRMSG(SCIDB_LE_INVALID_OFFSET_REQUESTED,            "Invalid offset requested");
ERRMSG(SCIDB_LE_CANT_MERGE_BITMASK,                  "Cannot merge bitmask with a larger payload");
ERRMSG(SCIDB_LE_NOT_IMPLEMENTED,                     "Feature '%1%' not yet implemented");
ERRMSG(SCIDB_LE_NO_CURRENT_ELEMENT,                  "No current element");
ERRMSG(SCIDB_LE_OPERATION_FAILED,                    "Operation '%1%' failed");
ERRMSG(SCIDB_LE_UNKNOWN_CONFIG_OPTION,               "Unknown config option '%1%'");
ERRMSG(SCIDB_LE_ERROR_NEAR_CONFIG_OPTION,            "Error '%1%' near config option '%2%'");
ERRMSG(SCIDB_LE_ERROR_IN_CONFIGURATION_FILE,         "Error '%1%' in configuration file");
ERRMSG(SCIDB_LE_FILE_NOT_FOUND,                      "File '%1%' not found");
ERRMSG(SCIDB_LE_ARRAY_VERSION_DOESNT_EXIST,          "Specified version of array '%1%' does not exist");
ERRMSG(SCIDB_LE_CANT_SEND_RECEIVE,                   "Cannot send or receive network messages");
ERRMSG(SCIDB_LE_CONNECTION_ERROR,                    "Error #%1% when connecting to %2%:%3%");
ERRMSG(SCIDB_LE_FUNCTION_NOT_FOUND,                  "Function '%1%' not found");
ERRMSG(SCIDB_LE_TYPE_CONVERSION_ERROR,               "Cannot convert type '%1%' into '%2%'");
ERRMSG(SCIDB_LE_TYPE_CONVERSION_ERROR2,              "Cannot convert '%1%' of type '%2%' into '%3%'");
ERRMSG(SCIDB_LE_REF_NOT_FOUND,                       "Reference '%1%' not found");
ERRMSG(SCIDB_LE_ERROR_IN_UDF,                        "Error '%1%' in UDF '%2%'");
ERRMSG(SCIDB_LE_UNKNOWN_ERROR_IN_UDF,                "Unknown error in UDF '%1%'");
ERRMSG(SCIDB_LE_TYPE_NOT_REGISTERED,                 "Type '%1%' is not registered");
ERRMSG(SCIDB_LE_TYPE_ALREADY_REGISTERED,             "Type '%1%' is already registered");
ERRMSG(SCIDB_LE_DIMENSION_NOT_EXIST,                 "Dimension '%1%' does not exist");
ERRMSG(SCIDB_LE_ATTRIBUTE_NOT_EXIST,                 "Attribute '%1%' does not exist");
ERRMSG(SCIDB_LE_CANT_FIND_CONVERTER,                 "Cannot find converter from type '%1%' to '%2%'");
ERRMSG(SCIDB_LE_CANT_FIND_IMPLICIT_CONVERTER,        "Cannot find implicit converter from type '%1%' to '%2%'");
ERRMSG(SCIDB_LE_PARAMETER_TYPE_ERROR,                "Operator expected expression of type '%1%' but passed nonconvertable type '%2%'");
ERRMSG(SCIDB_LE_DISTRIBUTION_SPECIFICATION_ERROR,    "Multi-child operators with specific distribution requirements not supported");
ERRMSG(SCIDB_LE_DISTRIBUTION_SPECIFICATION_ERROR2,   "Operators with more than two input arrays may only require distribution ANY or COLLOCATED");
ERRMSG(SCIDB_LE_LOGICAL_OP_DOESNT_EXIST,             "Logical operator '%1%' does not exist");
ERRMSG(SCIDB_LE_PHYSICAL_OP_DOESNT_EXIST,            "Physical operator '%1%' for logical operator '%2%' does not exist");
ERRMSG(SCIDB_LE_LOGICAL_OP_ALREADY_REGISTERED,       "Logical operator '%1%' already registered");
ERRMSG(SCIDB_LE_PHYSICAL_OP_ALREADY_REGISTERED,      "Physical operator '%1%' for logical operator '%2%' already registered");
ERRMSG(SCIDB_LE_QUERY_CANCELLED,                      "Query %1% was cancelled");
ERRMSG(SCIDB_LE_NO_QUORUM,                           "Instance liveness has changed");
ERRMSG(SCIDB_LE_QUERY_NOT_FOUND,                     "Query %1% not found");
ERRMSG(SCIDB_LE_QUERY_NOT_FOUND2,                    "Query already deallocated/cancelled");
ERRMSG(SCIDB_LE_QUERY_WAS_EXECUTED,                  "Query was executed previously");
ERRMSG(SCIDB_LE_MEMORY_ALLOCATION_ERROR,             "Error '%1%' during memory allocation");
ERRMSG(SCIDB_LE_REDISTRIBUTE_ERROR,                  "Attempt to redistribute on undefined partitioning schema");
ERRMSG(SCIDB_LE_QUERY_PARSING_ERROR,                 "Query parser failed with error '%1%'");
ERRMSG(SCIDB_LE_SUBQUERIES_NOT_SUPPORTED,           "Subqueries inside expressions not supported");
ERRMSG(SCIDB_LE_WRONG_ASTERISK_USAGE,               "Asterisk can be used only in aggregates");
ERRMSG(SCIDB_LE_ARRAY_NAME_REQUIRED,                "CREATE ARRAY statement requires array name");
ERRMSG(SCIDB_LE_ARRAY_ALREADY_EXIST,                "Array '%1%' already exists");
ERRMSG(SCIDB_LE_DUPLICATE_DIMENSION_NAME,           "Cannot create dimension '%1%'; name collides with existing object");
ERRMSG(SCIDB_LE_REFERENCE_NOT_ALLOWED_IN_DEFAULT,   "References not allowed in DEFAULT clause");
ERRMSG(SCIDB_LE_NULL_IN_NON_NULLABLE,               "Default value for non-nullable attribute '%1%' cannot be null");
ERRMSG(SCIDB_LE_COMPRESSOR_DOESNT_EXIST,            "Compressor with name '%1%' does not exist");
ERRMSG(SCIDB_LE_UNEXPECTED_OPERATOR_ARGUMENT,       "Operator '%1%' does not take an argument but was passed '%2%'");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT,     "Operator '%1%' expected %2% argument(s) but was passed %3%");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT2,    "Operator '%1%' expected more arguments");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENTS_COUNT3,    "Operator '%1%' expected only %2% arguments");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENT,            "Expected '%1%' in position %2% of operator '%3%' but found '%4%'");
ERRMSG(SCIDB_LE_NESTED_ARRAYS_NOT_SUPPORTED,        "Nested arrays not supported");
ERRMSG(SCIDB_LE_NO_MAPPING_ARRAY,                   "There is no mapping array for dimensions '%1%' in array '%2%'");
ERRMSG(SCIDB_LE_AMBIGUOUS_OPERATOR_PARAMETER,       "Parameter of operator is ambiguous");
ERRMSG(SCIDB_LE_WRONG_OPERATOR_ARGUMENT2,           "Parameter must be %1%");
ERRMSG(SCIDB_LE_AMBIGUOUS_ATTRIBUTE,                "Attribute '%1%' is ambiguous");
ERRMSG(SCIDB_LE_AMBIGUOUS_DIMENSION,                "Dimension '%1%' is ambiguous");
ERRMSG(SCIDB_LE_UNEXPECTED_OPERATOR_IN_EXPRESSION,  "Array operators cannot be used inside scalar expressions");
ERRMSG(SCIDB_LE_WRONG_AGGREGATE_ARGUMENTS_COUNT,    "An aggregate call must have exactly one argument");
ERRMSG(SCIDB_LE_WRONG_AGGREGATE_ARGUMENT,           "An aggregate call must contain a single attribute reference, SELECT statement or *");
ERRMSG(SCIDB_LE_REFERENCE_EXPECTED,                 "Attribute or dimension reference expected");
ERRMSG(SCIDB_LE_SORTING_QUIRK_WRONG_USAGE,          "Parser error: incorrect usage of SORT qualifier");
ERRMSG(SCIDB_LE_SELECT_IN_AGGREGATE_WRONG_USAGE,    "SciDB supports only simple SELECT statements inside aggregates");
ERRMSG(SCIDB_LE_TIMESTAMP_IN_AGGREGATE_WRONG_USAGE, "Timestamp cannot be used inside aggregate");
ERRMSG(SCIDB_LE_UNKNOWN_ARRAY_REFERENCE,            "Unknown array reference");
ERRMSG(SCIDB_LE_AGGREGATE_EXPECTED,                 "SELECT list items must contain a single aggregate if FROM is omitted");
ERRMSG(SCIDB_LE_WRONG_AGGREGATE_ARGUMENT2,          "An aggregate call must contain a single attribute reference or SELECT statement");
ERRMSG(SCIDB_LE_SINGLE_ATTRIBUTE_IN_INPUT_EXPECTED, "Input must have one attribute for aggregating in this form");
ERRMSG(SCIDB_LE_UNKNOWN_ATTRIBUTE_OR_DIMENSION,     "Attribute or dimension reference '%1%' does not exists");
ERRMSG(SCIDB_LE_AMBIGUOUS_ATTRIBUTE_OR_DIMENSION,   "Attribute or dimension reference '%1%' is ambiguous");
ERRMSG(SCIDB_LE_INPUT_EXPECTED,                     "Array name, array operator or SELECT statement expected");
ERRMSG(SCIDB_LE_CAN_NOT_STORE,                      "Cannot STORE or REDIMENSION_STORE output array into '%1%'. Schemas do not conform.");
ERRMSG(SCIDB_LE_AGGREGATE_CANT_BE_NESTED,           "Aggregate calls cannot be nested");
ERRMSG(SCIDB_LE_UNEXPECTED_SELECT_INSIDE_AGGREGATE, "SELECT inside aggregate not implemented");
ERRMSG(SCIDB_LE_ITEM_MUST_BE_INSIDE_AGGREGATE,      "SELECT item must be inside aggregate function");
ERRMSG(SCIDB_LE_ITEM_MUST_BE_INSIDE_AGGREGATE2,     "SELECT item must be constant or be inside aggregate function");
ERRMSG(SCIDB_LE_WRONG_REGRID_REDIMENSION_SIZES_COUNT,"REGRID and WINDOW clause must contain sizes for each dimension");
ERRMSG(SCIDB_LE_INJECTED_ERROR,                     "Injected error");
ERRMSG(SCIDB_LE_ERRNS_CAN_NOT_BE_UNREGISTERED,      "Error namespace '%1%' cannot be unregistered");
ERRMSG(SCIDB_LE_STORAGE_CLOSE_FAILED,               "Storage closed with errors");
ERRMSG(SCIDB_LE_UNKNOWN_MESSAGE_TYPE,               "Unknown/unexpected message type '%1%'");
ERRMSG(SCIDB_LE_IQUERY_PARSER_ERROR,                "Iquery parser error: '%1%'");
ERRMSG(SCIDB_LE_STORAGE_ALREADY_REGISTERED,         "Instance #%1% already registered in system catalog");
ERRMSG(SCIDB_LE_STORAGE_NOT_REGISTERED,             "Storage is not registered in system catalog");
ERRMSG(SCIDB_LE_CANT_ACCEPT_CONNECTION,             "Error #%1% (%2%) when accepting connection");
ERRMSG(SCIDB_LE_UNKNOWN_MESSAGE_TYPE2,              "Invalid message type for ID");
ERRMSG(SCIDB_LE_INVALID_SHEDULER_WORK_ITEM,         "Invalid work item for Scheduler");
ERRMSG(SCIDB_LE_INVALID_SHEDULER_PERIOD,            "Invalid period for Scheduler");
ERRMSG(SCIDB_LE_CONNECTION_ERROR2,                  "Connection error while sending");
ERRMSG(SCIDB_LE_CANT_OPEN_PATH,                     "Cannot open path '%1%'");
ERRMSG(SCIDB_LE_DIRECTORY_EXPECTED,                 "Path '%1%' is not directory");
ERRMSG(SCIDB_LE_BINDING_NOT_SUPPORTED,              "This binding not supported");
ERRMSG(SCIDB_LE_WRONG_ATTRIBUTE_TYPE,               "Attribute '%1%' has incorrect datatype (source: %2%, destination: %3%)");
ERRMSG(SCIDB_LE_WRONG_ATTRIBUTE_FLAGS,              "Attribute '%1%' has incorrect properties");
ERRMSG(SCIDB_LE_WRONG_SOURCE_ATTRIBUTE_TYPE,        "Source attribute '%1%' must be of type '%2%'");
ERRMSG(SCIDB_LE_WRONG_SOURCE_ATTRIBUTE_FLAGS,       "Source attribute '%1%' must not have special properties");
ERRMSG(SCIDB_LE_WRONG_DESTINATION_ATTRIBUTE_TYPE,   "Destination attribute '%1%' must be of type '%2%'");
ERRMSG(SCIDB_LE_WRONG_DESTINATION_ATTRIBUTE_FLAGS,  "Destination attribute '%1%' must not have special properties");
ERRMSG(SCIDB_LE_WRONG_SOURCE_DIMENSION_TYPE,        "Source dimension '%1%' must be of type '%2%'");
ERRMSG(SCIDB_LE_WRONG_DESTINATION_DIMENSION_TYPE,   "Destination dimenstion '%1%' must be of type '%2%'");
ERRMSG(SCIDB_LE_DIMENSIONS_DONT_MATCH,              "Dimensions '%1%' and '%2%' do not match");
ERRMSG(SCIDB_LE_UNEXPECTED_DESTINATION_DIMENSION,   "No data provided for destination dimension '%1%'");
ERRMSG(SCIDB_LE_UNEXPECTED_DESTINATION_ATTRIBUTE,   "No data provided for destination attribute '%1%'");
ERRMSG(SCIDB_LE_WRONG_DIMENSION_TYPE,               "Dimension '%1%' has incorrect datatype (source: %2%, destination: %3%)");
ERRMSG(SCIDB_LE_AGGREGATE_RESULT_CANT_BE_TRANSFORMED_TO_DIMENSION,"Aggregate result '%1%' cannot be transformed into a dimension");
ERRMSG(SCIDB_LE_CHUNK_WRONG_ITERATION_MODE,         "Operator does not support the requested chunk iteration mode");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR1,                  "The substitute array '%1%' must have only one dimension");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR2,                  "The substitute array '%1%' must have only one attribute");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR3,                  "The dimension '%1%' must be integer");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR4,                  "The dimension must start at 0");
ERRMSG(SCIDB_LE_SUBSTITUTE_ERROR5,                  "Input attribute '%1%' does not match the datatype of '%2%'");
ERRMSG(SCIDB_LE_LOGICAL_JOIN_ERROR1,                "Join must be applied to arrays of same dimensionality");
ERRMSG(SCIDB_LE_LOGICAL_JOIN_ERROR2,                "Joined arrays have different schemas");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR1,                 "Multiply only defined for double, float, int64, int32 and int16");
ERRMSG(SCIDB_LE_LIST_ERROR1,                        "Parameter of 'list' operator can be 'aggregates', 'arrays', 'operators', 'types', 'functions', 'queries', 'libraries', 'instances'");
ERRMSG(SCIDB_LE_PATH_IS_EMPTY,                      "Given dir path is empty");
ERRMSG(SCIDB_LE_CANT_CREATE_DIRECTORY,              "Cannot create directory '%1%'");
ERRMSG(SCIDB_LE_EXPLAIN_ERROR1,                     "Operator 'explain_physical' accepts 1 or 2 parameters only");
ERRMSG(SCIDB_LE_EXPLAIN_ERROR2,                     "Second parameter of 'explain_logical' operator must be 'aql' or 'afl'");
ERRMSG(SCIDB_LE_OPERATION_NOT_FOUND,                "Operation '%1%' not defined for type '%2%'");
ERRMSG(SCIDB_LE_NO_MAPPING_FOR_COORDINATE,          "No mapping for such coordinate value");
ERRMSG(SCIDB_LE_UNDEFINED_DISTRIBUTION_CANT_HAVE_MAPPER,"An undefined distribution cannot have a mapper");
ERRMSG(SCIDB_LE_SPECIFIC_DISTRIBUTION_REQUIRED,     "Specific requirements must be provided IFF required distribution is specific");
ERRMSG(SCIDB_LE_CANT_GET_SYSTEM_TIME,               "Cannot get system time");
ERRMSG(SCIDB_LE_TIMER_RETURNED_UNEXPECTED_ERROR,    "Timer (expires_from_now) returned unexpected error '%1%'");
ERRMSG(SCIDB_LE_TIMER_RETURNED_UNEXPECTED_ERROR2,   "Timer handler returned unexpected error '%1%'");
ERRMSG(SCIDB_LE_CANT_LINK_DATA_TO_ZERO_BUFFER,      "Cannot link data to zero length buffer");
ERRMSG(SCIDB_LE_CANT_MODIFY_VALUE_WITH_LINKED_DATA, "Cannot modify value object with linked data");
ERRMSG(SCIDB_LE_CANT_SET_VALUE_VECTOR_TO_DEFAULT,   "Cannot set value vector to default");
ERRMSG(SCIDB_LE_CANT_ADD_NULL_FACTORY,              "Cannot add NULL factory to Aggregate Library");
ERRMSG(SCIDB_LE_DUPLICATE_AGGREGATE_FACTORY,        "Cannot add duplicate factory to Aggregate Library");
ERRMSG(SCIDB_LE_CANT_INCREMENT_LOCK,                "Cannot increment lock counter for '%1%' because query was cancelled");
ERRMSG(SCIDB_LE_DIMENSIONS_MISMATCH,                "Dimension mismatch");
ERRMSG(SCIDB_LE_CHUNK_ALREADY_EXISTS,               "An existing chunk cannot be updated");
ERRMSG(SCIDB_LE_CANT_MERGE_CHUNKS_WITH_VARYING_SIZE,"Merge of chunks with varying size attribute type is not supported");
ERRMSG(SCIDB_LE_CANT_UPDATE_READ_ONLY_CHUNK,        "Chunk is read-only and cannot be updated");
ERRMSG(SCIDB_LE_TYPE_MISMATCH_BETWEEN_AGGREGATE_AND_CHUNK,"Type mismatch between aggregate and chunk");
ERRMSG(SCIDB_LE_AGGREGATE_STATE_MUST_BE_NULLABLE,   "Aggregate NULL flag must be TRUE");
ERRMSG(SCIDB_LE_EXTRACT_EXPECTED_FIXED_SIZE_ATTRIBUTE,"Extract attribute should be fixed size");
ERRMSG(SCIDB_LE_EXTRACT_UNEXPECTED_BOOLEAN_ATTRIBUTE,"Extract attribute cannot have boolean type");
ERRMSG(SCIDB_LE_WRONG_NUMBER_OF_DIMENSIONS,         "Wrong number of dimensions");
ERRMSG(SCIDB_LE_UNALIGNED_COORDINATES,              "Coordinates should be aligned on chunk boundary");
ERRMSG(SCIDB_LE_CANT_ALLOCATE_MEMORY,               "Failed to allocate memory");
ERRMSG(SCIDB_LE_NO_CURRENT_CHUNK,                   "No current chunk");
ERRMSG(SCIDB_LE_CHUNK_OUT_OF_BOUNDARIES,            "Chunk is outside of array boundaries");
ERRMSG(SCIDB_LE_ACCESS_TO_EMPTY_CELL,               "Access to empty cell");
ERRMSG(SCIDB_LE_ASSIGNING_NULL_TO_NON_NULLABLE,     "Assigning NULL to non-nullable attribute");
ERRMSG(SCIDB_LE_CANT_USE_TILE_MODE_FOR_APPEND,      "Cannot use tile mode for append");
ERRMSG(SCIDB_LE_TILE_NOT_ALIGNED,                   "Tile position is not correctly aligned");
ERRMSG(SCIDB_LE_TILE_MODE_EXPECTED_STRIDE_MAJOR_ORDER,"Tiles can only be written in stride major order");
ERRMSG(SCIDB_LE_INVALID_OPERATION_FOR_SEQUENTIAL_MODE,"Invalid operation for sequential mode");
ERRMSG(SCIDB_LE_CANT_UPDATE_BITMAP_IN_TILE_MODE,    "Cannot update bitmap in tile mode");
ERRMSG(SCIDB_LE_NO_ASSOCIATED_BITMAP_CHUNK,         "No associated bitmap chunk");
ERRMSG(SCIDB_LE_NO_CURRENT_BITMAP_CHUNK,            "No current bitmap chunk");
ERRMSG(SCIDB_LE_CANT_FETCH_CHUNK_BODY,              "Failed to fetch chunk body");
ERRMSG(SCIDB_LE_STRIDE_SHOULD_BE_BYTE_ALIGNED,      "Stride should be byte aligned");
ERRMSG(SCIDB_LE_MULTIDIMENSIONAL_ARRAY_NOT_ALLOWED, "Multidimensional array is not allowed");
ERRMSG(SCIDB_LE_NO_DATA_FOR_INITIALIZE,             "Nothing to initialize data from");
ERRMSG(SCIDB_LE_COMPRESSION_DESTINATION_BITMAP_NOT_EMPTY,"Compression destination bitmap not empty");
ERRMSG(SCIDB_LE_OP_SAMPLE_ERROR1,                     "Seed should be a positive integer");
ERRMSG(SCIDB_LE_OP_SAMPLE_ERROR2,                     "Probability should be in interval  (0..1]");
ERRMSG(SCIDB_LE_INVALID_INSTANCE_ID,                    "Invalid instance ID: '%1%'");
ERRMSG(SCIDB_LE_ARRAYS_NOT_CONFORMANT,              "Arrays are not conformant");
ERRMSG(SCIDB_LE_UNTERMINATED_CHARACTER_CONSTANT,    "Unterminated character constant");
ERRMSG(SCIDB_LE_UNTERMINATED_STRING_LITERAL,        "Unterminated string literal");
ERRMSG(SCIDB_LE_BAD_LITERAL,                        "Bad literal");
ERRMSG(SCIDB_LE_OP_STORE_ERROR1,                    "Arrays with user-defined coordinates can only be updated using REDIMENSION_STORE");
ERRMSG(SCIDB_LE_OP_REDIMENSION_ERROR1,              "Destination array for REDIMENSION must have EMPTY flag TRUE");
ERRMSG(SCIDB_LE_NO_MEMORY_TO_ALLOCATE_MATRIX,       "Not enough memory to allocate matrix");
ERRMSG(SCIDB_LE_NO_MEMORY_TO_ALLOCATE_VECTOR,       "Not enough memory to allocate vector");
ERRMSG(SCIDB_LE_CANT_UPDATE_CHUNK,                  "Cannot update disk chunk");
ERRMSG(SCIDB_LE_INVALID_REDUNDANCY,                 "Redundancy should be smaller than number of instances");
ERRMSG(SCIDB_LE_INSTANCE_OFFLINE,                       "Instance #%1% is offline");
ERRMSG(SCIDB_LE_DIVISION_BY_ZERO,                   "Division by zero");
ERRMSG(SCIDB_LE_FAILED_PARSE_STRING,                "Failed to parse string");
ERRMSG(SCIDB_LE_DIMENSION_EXPECTED,                 "Dimension has to be specified");
ERRMSG(SCIDB_LE_CANT_CONVERT_ARRAY_TO_SCALAR,       "Array cannot be converted to scalar");
ERRMSG(SCIDB_LE_REDISTRIBUTE_AGGREGATE_ERROR1,      "Empty tag attribute should be last and cannot be aggregated");
ERRMSG(SCIDB_LE_REDISTRIBUTE_ERROR1,                "Empty tag attribute should be last");
ERRMSG(SCIDB_LE_CANT_MERGE_READONLY_CHUNK,          "Cannot merge read-only chunk");
ERRMSG(SCIDB_LE_TOO_MANY_COORDINATES,               "Too many coordinate values for the specified dimension");
ERRMSG(SCIDB_LE_CANT_REDIMENSION_NULL,              "Null cannot be redimensioned");
ERRMSG(SCIDB_LE_INVALID_SPECIFIED_DATE,             "Specified date is not valid");
ERRMSG(SCIDB_LE_CANT_CONVERT_NULL,                  "Cannot convert NULL value");
ERRMSG(SCIDB_LE_NO_QUORUM2,                         "Not enough online instances to execute query");
ERRMSG(SCIDB_LE_OP_REGRID_ERROR1,                   "Regrid interval should be positive");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR1,                   "Window size should be positive");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR2,                   "Window doesn't fit in overlap area");
ERRMSG(SCIDB_LE_OP_BUILD_ERROR1,                    "Build expression should not access attributes");
ERRMSG(SCIDB_LE_OP_BUILD_ERROR2,                    "Constructed array should have one attribute");
ERRMSG(SCIDB_LE_OP_BUILD_ERROR3,                    "Array with open boundary cannot be built");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR1,             "Build_sparse expression should not access attributes");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR2,             "Build_sparse predicate should not access attributes");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR3,             "Constructed array should have one attribute");
ERRMSG(SCIDB_LE_OP_BUILD_SPARSE_ERROR4,             "Cannot BUILD array with open boundary");
ERRMSG(SCIDB_LE_OP_CAST_ERROR1,                     "Mismatched number of attributes");
ERRMSG(SCIDB_LE_OP_CAST_ERROR2,                     "Mismatched attributes types");
ERRMSG(SCIDB_LE_OP_CAST_ERROR3,                     "Mismatched attributes flags");
ERRMSG(SCIDB_LE_OP_CAST_ERROR4,                     "Mismatched number of dimensions");
ERRMSG(SCIDB_LE_OP_CAST_ERROR5,                     "Dimension length doesn't match");
ERRMSG(SCIDB_LE_OP_CAST_ERROR6,                     "Dimension start doesn't match");
ERRMSG(SCIDB_LE_OP_CAST_ERROR7,                     "Dimension chunk size doesn't match");
ERRMSG(SCIDB_LE_OP_CAST_ERROR8,                     "Dimension chunk overlap doesn't match");
ERRMSG(SCIDB_LE_OP_CONCAT_ERROR1,                   "Arrays with open boundary cannot be concatenated");
ERRMSG(SCIDB_LE_OP_CROSSJOIN_ERROR1,                "Dimension should be specified only once in JOIN ON list");
ERRMSG(SCIDB_LE_OP_DELDIM_ERROR1,                   "Cannot delete last dimension of array");
ERRMSG(SCIDB_LE_OP_DELDIM_ERROR2,                   "Only dimension with length 1 can be removed");
ERRMSG(SCIDB_LE_OP_REDIMENSION_ERROR2,              "The result of an aggregate cannot be transformed into a dimension");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR1,        "Resulting array has no dimensions");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR2,        "Destination array for REDIMENSION should have EMPTY flag TRUE");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR3,        "REDIMENSION_STORE cannot fill overlap area larger than chunk interval");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR4,        "Dimension '%1%' is not compatible");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR5,        "Attribute '%1%' cannot be transformed into a dimension");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR1,                    "Out-of-sequence chunk in input file");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR2,                    "Input parser expected '%1%'");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR3,                    "Input parser expected coordinate");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR4,                    "Invalid chunk position");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR5,                    "Duplicate chunk address");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR6,                    "Too much nesting");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR7,                    "Out of bounds");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR8,                    "Input parser expected literal");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR9,                    "No values for empty cells should be defined: only () is accepted");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR10,                   "Invalid format for input file");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR11,                   "Chunk is out of window boundary");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR12,                   "Unterminated character constant");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR13,                   "Unterminated string literal");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR14,                   "Bad literal");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR1,                  "This matrix cannot be inverted (the matrix contains a zero row or the determinant is zero)");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR2,                  "Determinant = 0.0, this matrix cannot be inverted");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR3,                  "Matrix must contain 1 attribute");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR4,                  "Matrix must contain attribute of type double");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR5,                  "Only 2-D matrices can be inverted");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR6,                  "Inversion only works on square matrices");
ERRMSG(SCIDB_LE_OP_INVERSE_ERROR7,                  "Cannot invert an unbounded matrix");
ERRMSG(SCIDB_LE_NO_CURRENT_POSITION,                "No current position");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR2,                 "Matrix must have 1 attrbiute");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR3,                 "Array must be rectangular matrix");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR4,                 "Cannot multiply unbounded matrices");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR5,                 "Matrix dimensions must match");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR6,                 "Matrix chunk sizes in the joint dimension must match");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR7,                 "Matrices to be multiplied should have the same attribute type");
ERRMSG(SCIDB_LE_OP_MULTIPLY_ERROR8,                 "Matrices with nullable attributes cannot be multiplied");
ERRMSG(SCIDB_LE_OPERATION_NOT_FOUND2,               "Operation '%1%' not defined for types '%2%' and '%3%'");
ERRMSG(SCIDB_LE_OP_NORMALIZE_ERROR1,                "Vector must contain 1 attribute");
ERRMSG(SCIDB_LE_OP_NORMALIZE_ERROR2,                "Array must be 1-D vector");
ERRMSG(SCIDB_LE_OP_REPART_ERROR1,                   "Mismatched number of dimensions");
ERRMSG(SCIDB_LE_OP_REPART_ERROR2,                   "Mismatched array coordinate type");
ERRMSG(SCIDB_LE_OP_REPART_ERROR3,                   "Mismatched array base");
ERRMSG(SCIDB_LE_OP_REPART_ERROR4,                   "Mismatched array length");
ERRMSG(SCIDB_LE_OP_REPART_ERROR5,                   "Array should have fixed lower boundary");
ERRMSG(SCIDB_LE_OP_RESHAPE_ERROR1,                  "Size of array should be fixed");
ERRMSG(SCIDB_LE_OP_RESHAPE_ERROR2,                  "Chunk should have no overlap");
ERRMSG(SCIDB_LE_OP_RESHAPE_ERROR3,                  "Incompatible array dimensions");
ERRMSG(SCIDB_LE_OP_REVERSE_ERROR1,                  "Only fixed-size array can be reversed");
ERRMSG(SCIDB_LE_OP_SLICE_ERROR1,                    "Input array has too few dimensions for slice");
ERRMSG(SCIDB_LE_OP_SLICE_ERROR2,                    "Slice coordinate is out of bounds");
ERRMSG(SCIDB_LE_OP_SORT_ERROR2,                     "Column index is out of range");
ERRMSG(SCIDB_LE_OP_SORT_ERROR3,                     "Cannot jump on more than one chunk forward");
ERRMSG(SCIDB_LE_OP_SORT_ERROR4,                     "Chunk out of window");
ERRMSG(SCIDB_LE_OP_THIN_ERROR1,                     "Step must be divider of chunk size");
ERRMSG(SCIDB_LE_OP_THIN_ERROR2,                     "Starting position is out of bounds");
ERRMSG(SCIDB_LE_OP_THIN_ERROR3,                     "Starting offset must be smaller than step");
ERRMSG(SCIDB_LE_OP_THIN_ERROR4,                     "Step must be smaller than chunk size");
ERRMSG(SCIDB_LE_OP_THIN_ERROR5,                     "Step must be positive number");
ERRMSG(SCIDB_LE_OP_TRANSPOSE_ERROR1,                "Cannot transpose an unbounded array");
ERRMSG(SCIDB_LE_OP_UNPACK_ERROR1,                   "Size of of array is not multiple of chunk size");
ERRMSG(SCIDB_LE_OP_XGRID_ERROR1,                    "Cannot xgrid an unbounded array");
ERRMSG(SCIDB_LE_OP_XGRID_ERROR2,                    "Xgrid arguments must be positive");
ERRMSG(SCIDB_LE_DIMENSION_START_CANT_BE_UNBOUNDED,  "Dimension start cannot be unbounded");
ERRMSG(SCIDB_LE_HIGH_SHOULDNT_BE_LESS_LOW,          "Upper boundary of dimension must be greater than lower boundary");
ERRMSG(SCIDB_LE_OVERLAP_CANT_BE_LARGER_CHUNK,       "Chunk overlap cannot be larger than chunk size");
ERRMSG(SCIDB_LE_DIMENSIONS_NOT_SPECIFIED,           "Must specify at least one element in the array");
ERRMSG(SCIDB_LE_PIN_UNPIN_DISBALANCE,               "pin/unpin disbalance or race condition during close");
ERRMSG(SCIDB_LE_COMPRESS_METHOD_NOT_DEFINED,        "Compression method is not defined for the chunk");
ERRMSG(SCIDB_LE_STORAGE_DESCRIPTOR_INVALID_FORMAT,  "Invalid format of storage description file");
ERRMSG(SCIDB_LE_CHUNK_NOT_FOUND,                    "Chunk not found");
ERRMSG(SCIDB_LE_NO_FREE_SPACE,                      "No more free space");
ERRMSG(SCIDB_LE_CHUNK_SIZE_TOO_LARGE,               "Chunk size %1% is larger than segment size %2%");
ERRMSG(SCIDB_LE_CANT_REALLOCATE_MEMORY,             "Failed to reallocate memory");
ERRMSG(SCIDB_LE_INVALID_LIVENESS,                   "Invalid liveness");
ERRMSG(SCIDB_LE_LIVENESS_MISMATCH,                  "Liveness mismatch");
ERRMSG(SCIDB_LE_MESSAGE_MISSED_QUERY_ID,            "Message has no query ID");
ERRMSG(SCIDB_LE_VARIABLE_SIZE_TYPES_NOT_SUPPORTED_BY_VAR,"Variable size types not supported by var");
ERRMSG(SCIDB_LE_MISMATCHED_COORDINATES_IN_PHYSICAL_BOUNDARIES,"Mismatched coordinates in physical boundaries");
ERRMSG(SCIDB_LE_DIMENSIONS_DONT_MATCH_COORDINATES,  "Dimensions don't match coordinates");
ERRMSG(SCIDB_LE_MISMATCHED_BOUNDARIES,              "Mismatched boundaries");
ERRMSG(SCIDB_LE_CANT_CREATE_BOUNDARIES_FROM_INFINITE_ARRAY,"Cannot create boundaries from infinite array");
ERRMSG(SCIDB_LE_LIVENESS_EMPTY,                     "Liveness unexpectedly contains no data");
ERRMSG(SCIDB_LE_DUPLICATE_QUERY_ID,                 "Query with same ID already exists in the system");
ERRMSG(SCIDB_LE_CANT_ACQUIRE_READ_LOCK,             "Failed to acquire a read lock");
ERRMSG(SCIDB_LE_CANT_GENERATE_UTC_TIME,             "Unable to generate UTC time");
ERRMSG(SCIDB_LE_CANT_CREATE_SG_WITH_UNDEFINED_DISTRIBUTION,"Cannot create an SG with undefined distribution");
ERRMSG(SCIDB_LE_MALFORMED_AGGREGATE,                "Malformed or unsupported aggregate");
ERRMSG(SCIDB_LE_CANT_LOCK_DATABASE,                 "Failed to get exclusive access to the database");
ERRMSG(SCIDB_LE_DATABASE_HEADER_CORRUPTED,          "Database header is corrupted");
ERRMSG(SCIDB_LE_CANT_DECOMPRESS_CHUNK,              "Failed to decompress chunk");
ERRMSG(SCIDB_LE_CHUNK_NOT_PINNED,                   "Accessed chunk should be pinned");
ERRMSG(SCIDB_LE_CHUNK_FILE_HAS_INVALID_NAME,        "Chunk file has invalid name");
ERRMSG(SCIDB_LE_DFS_DIRECTORY_NOT_EXIST,            "DFS directory does not exist");
ERRMSG(SCIDB_LE_INVALID_MONTH_REPRESENTATION,       "Invalid month representation: %1%");
ERRMSG(SCIDB_LE_INVALID_USER_ERROR_CODE,            "Cannot register error namespace '%1%' with error code '%2%': user-defined error codes must be greater than %3%. Use constant SCIDB_USER_ERROR_CODE_START to define your first error code.");
ERRMSG(SCIDB_LE_ATTRIBUTES_MISMATCH,                "Attributes mismatch");
ERRMSG(SCIDB_LE_INVALID_FUNCTION_ARGUMENT,          "Invalid function argument: %1%");
ERRMSG(SCIDB_LE_LOGICAL_CHUNK_SIZE_TOO_LARGE,       "Chunk size should not exceed 2^64");
ERRMSG(SCIDB_W_FILE_NOT_FOUND_ON_INSTANCES,         "File '%1%' not found on instance(s) %2%");
ERRMSG(SCIDB_LE_FILE_IMPORT_FAILED,                 "Import from file '%1%' (instance %2%) to array '%3%' failed at line %4%, column %5%, offset %6%, value='%7%': %8%");
ERRMSG(SCIDB_LE_ACCESS_TO_RAW_CHUNK,                "Access to raw chunk of array '%3%'");
ERRMSG(SCIDB_LE_INVALID_COMMIT_STATE,              "'%2%' request for query (%1%) is invalid in the current state");
ERRMSG(SCIDB_LE_ARRAY_VERSION_DOESNT_EXIST2,        "Array '%1%' is immutable and does not have versions");
ERRMSG(SCIDB_LE_WRONG_ASTERISK_USAGE2,              "Asterisk for all array versions access can be used only in SELECT");
ERRMSG(SCIDB_LE_LE_CANT_ACCESS_INDEX_FOR_ALLVERSIONS,"Only index of specified array version can be accessed");
ERRMSG(SCIDB_LE_CANT_ACCESS_ARRAY_VERSION,          "Array version inaccessible in this context");
ERRMSG(SCIDB_LE_CANT_ACCESS_INDEX_ARRAY,            "Index array inaccessible in this context");
ERRMSG(SCIDB_LE_CANT_UNLOAD_MODULE,                 "Cannot unload module '%1%'. The module is not loaded");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR6,        "Aggregate '%1%' doesn't match with any attribute");
ERRMSG(SCIDB_LE_SUBSTITUTE_FAILED,                  "Failed to substitute missing reason '%1%'");
ERRMSG(SCIDB_LE_REMOVE_NOT_POSSIBLE,                "Remove of array is not possible because it is still in use");
ERRMSG(SCIDB_LE_TRUNCATION,                         "Varying size type with length %1% cannot be converted to fixed size type with limit %2%"); 
ERRMSG(SCIDB_LE_LOOKUP_BAD_PARAM,                   "Number of attributes in pattern array of LOOKUP should match number of dimensions in source array"); 
ERRMSG(SCIDB_LE_INVALID_STORAGE_HEADER,             "Invalid storage header format");
ERRMSG(SCIDB_LE_MISMATCHED_STORAGE_FORMAT_VERSION,  "Mismatched storage format version: %1% instead of %2% required");
ERRMSG(SCIDB_LE_OP_CROSSJOIN_ERROR2,                "Joined dimensions should be specified for both arrays");
ERRMSG(SCIDB_LE_OP_NORMALIZE_ERROR3,                "Attribute must be of double type");
ERRMSG(SCIDB_LE_EXPLICIT_EMPTY_FLAG_NOT_ALLOWED,    "Explicit empty flag attribute not allowed. Use EMPTY keyword");
ERRMSG(SCIDB_LE_OP_CAST_ERROR9,                     "Dimension type doesn't match");
ERRMSG(SCIDB_LE_INCONSISTENT_ARRAY_DESC,            "Array descriptor is inconsistent");
ERRMSG(SCIDB_LE_FUNC_MAP_TRANSFORMATION_NOT_POSSIBLE, "Unable to perform requested functional mapping transformation");
ERRMSG(SCIDB_LE_OP_REDIMENSION_STORE_ERROR7,        "Too many duplicates for REDIMENSION_STORE with synthetic dimension: increase chunk size");
ERRMSG(SCIDB_LE_QUERY_ALREADY_COMMITED,              "Operation not possible because the query (%1%) already commited");
ERRMSG(SCIDB_LE_NETWORK_QUEUE_FULL,                  "Network queue is full");
ERRMSG(SCIDB_LE_CAN_NOT_CHANGE_MAPPING,             "Cannot change coordinates mapping for non-versioned array %1%");
ERRMSG(SCIDB_LE_INVALID_MESSAGE_FORMAT,             "Invalid message format for type %1%");
ERRMSG(SCIDB_LE_INVALID_ARRAY_LITERAL,              "Build required constant string when array literal flag is true");
ERRMSG(SCIDB_LE_INVALID_REDIMENSION_POSITION,       "Cannot redimension coordinates %1%; the position is not valid in the destination array");
ERRMSG(SCIDB_LE_SYSCALL_ERROR,                      "Invocation of %1% failed with return code=%2%, error=%3%, arg(s)=%4%");
ERRMSG(SCIDB_LE_NON_FQ_PATH_ERROR,                  "Path %1% is not fully qualified");
ERRMSG(SCIDB_LE_UNKNOWN_CTX,                        "Unknown/unexpected context type '%1%'");
ERRMSG(SCIDB_LE_CANT_LOCK_FILE,                     "Failed to get exclusive access to the file %1%");
ERRMSG(SCIDB_LE_TEMPLATE_PARSE_ERROR,               "Failed to parser template at position %1%");
ERRMSG(SCIDB_LE_TEMPLATE_FIXED_SIZE_TYPE,           "Length should not be explcitly specified for fixed size type %1%");
ERRMSG(SCIDB_LE_FILE_WRITE_ERROR,                   "Failed to write file: %1%");
ERRMSG(SCIDB_LE_FILE_READ_ERROR,                    "Failed to read file: %1%");
ERRMSG(SCIDB_LE_UNSUPPORTED_FORMAT,                 "Unsupported format: %1%");
ERRMSG(SCIDB_LE_MULTIPLE_DIMENSION_SPECIFICATION,   "Same dimension specified multiple times");
ERRMSG(SCIDB_LE_NOT_ENOUGH_DIMENSIONS_IN_SPECIFICATION,"Not all dimensions were specified");
ERRMSG(SCIDB_LE_PARTITION_NAME_NOT_UNIQUE,          "Partition name should be unique");
ERRMSG(SCIDB_LE_PARTITION_NAME_NOT_SPECIFIED,       "Partition name not specified");
ERRMSG(SCIDB_LE_UNKNOWN_PARTITION_NAME,             "Unknown partition name");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR3,                   "PRECEDING and FOLLOWING must be non-negative values");
ERRMSG(SCIDB_LE_WRONG_OVER_USAGE,                   "OVER keyword can only be applied to aggregates");
ERRMSG(SCIDB_W_MISSING_REASON_OUT_OF_BOUNDS,        "Missing reason cannot be imported in binary file");
ERRMSG(SCIDB_LE_DDL_CANT_BE_NESTED,                 "DDL operators cannot be nested");
ERRMSG(SCIDB_LE_NO_OPERATOR_RESULT,                 "Nested operator not returned any result to parent");
ERRMSG(SCIDB_LE_CATALOG_NEWER_THAN_SCIDB,           "Cannot connect SciDB with metadata version %1% to catalog with metadata version %2%");
ERRMSG(SCIDB_LE_CATALOG_METADATA_UPGRADE_ERROR,     "Catalog metadata upgrade failed with error: %1%");
ERRMSG(SCIDB_LE_DDL_SHOULDNT_HAVE_INPUTS,           "DDL operators cannot accept input arrays");
ERRMSG(SCIDB_LE_UNSUPPORTED_INPUT_ARRAY,            "Operator %1% does not support the given virtual input array. Consider splitting the query and using store() to create a temporary result");
ERRMSG(SCIDB_LE_OP_WINDOW_ERROR4,                   "Window size should be greater than 1");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR15,                   "Expected boolean constant for empty indicator");
ERRMSG(SCIDB_LE_OP_INPUT_ERROR16,                   "Number errors exceeds threshold");
ERRMSG(SCIDB_LE_CHUNK_SIZE_MUST_BE_POSITIVE,        "Chunk size must be positive");
ERRMSG(SCIDB_LE_OPERATION_FAILED_WITH_ERRNO,        "Operation %1% failed with errno %2%");
ERRMSG(SCIDB_LE_OP_RLE_EXPECTED,                    "Chunk expected to be in RLE format");
ERRMSG(SCIDB_LE_OP_NONEMPTY_EXPECTED,               "Non-emptyable array expected");
//Next ERRMSG

ERRMSG(SCIDB_LE_PG_QUERY_EXECUTION_FAILED,          "Execution of query '%1%' failed with error %2%");
ERRMSG(SCIDB_LE_LIBPQ_NOT_THREADSAFE,               "libpq is not threadsafe. Rebuild it with option --enable-thread-safety");
ERRMSG(SCIDB_LE_CANT_CONNECT_PG,                    "Cannot connect to PostgreSQL catalog: '%1%'");
ERRMSG(SCIDB_LE_UNREACHABLE_CODE,                   "Fatal: Unreachable code is reached in '%1%'");

// Copied from P4
ERRMSG(SCIDB_LE_DLA_ERROR13,                        "Request for unknown attribute");
ERRMSG(SCIDB_LE_DLA_ERROR14,                        "Specified attribute not found in array");
ERRMSG(SCIDB_LE_DLA_ERROR15,                        "Ranked attribute cannot be an empty indicator");
ERRMSG(SCIDB_LE_DLA_ERROR16,                        "Specified dimension not found in array");
ERRMSG(SCIDB_LE_DLA_ERROR17,                        "The number of samples passed to quantile must be at least 1");
