/*
**
* BEGIN_COPYRIGHT
*
* This file is part of SciDB.
* Copyright (C) 2008-2012 SciDB, Inc.
*
* SciDB is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation version 3 of the License.
*
* SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
* INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
* NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
* the GNU General Public License for the complete license terms.
*
* You should have received a copy of the GNU General Public License
* along with SciDB.  If not, see <http://www.gnu.org/licenses/>.
*
* END_COPYRIGHT
*/

/**
 * @file Network.h
 * @brief API allowing for sending and receiving network messages
 */

#ifndef NETWORK_H_
#define NETWORK_H_

#include <boost/asio.hpp>
#include <boost/function.hpp>
#include <boost/shared_ptr.hpp>
#include <google/protobuf/message.h>
#include <util/Semaphore.h>
#include <util/NetworkMessage.h>
#include <array/Metadata.h>

namespace scidb
{
   /**
    * Network message descriptor
    */
   class MessageDescription
   {
   public:
      virtual NodeID getSourceNodeID() const = 0;
      virtual MessagePtr getRecord() = 0;
      virtual MessageID getMessageType() const = 0;
      virtual boost::asio::const_buffer getBinary() = 0;
      virtual ~MessageDescription() {}
   };

   /**
    * Network message factory allows for addition of network message handlers
    * on SciDB server (only).
    */
   class NetworkMessageFactory
   {
   public:
      typedef boost::function< MessagePtr(MessageID) > MessageCreator;
      typedef boost::function< void(const boost::shared_ptr<MessageDescription>& ) > MessageHandler;

      virtual bool isRegistered(const MessageID& msgID) = 0;
      virtual bool addMessageType(const MessageID& msgID,
                                  const MessageCreator& msgCreator,
                                  const MessageHandler& msgHandler) = 0;
      virtual MessagePtr createMessage(const MessageID& msgID) = 0;
      virtual MessageHandler getMessageHandler(const MessageID& msgID) = 0;
      virtual ~NetworkMessageFactory() {}
   };

   /**
    * Network message factory access method
    * @return an instance of the factory
    */
   boost::shared_ptr<NetworkMessageFactory> getNetworkMessageFactory();

   /**
    * Return a reference to the io service object to schedule timers
    * @note XXX:
    * it might be better not to expose the io service directly but rather
    * provide a speicific functionality API (e.g. scheduleTimer())
    */
   boost::asio::io_service& getIOService();

   /**
    * A scheduler  that runs *at most* every specified period.
    * It schedules itself to run in max(0, ((lastTime + period) - currentTime)) seconds.
    * It is not recurring - every execution needs to be explicitly scheduled.
    * When scheduled for the first time, it is run immediately.
    */
   class Scheduler
   {
   public:
      typedef boost::function<void()> Work;
      virtual void schedule() = 0;
      virtual ~Scheduler() {}
   };

   /**
    * Get a scheduler for a given time period
    *
    * @param workItem  to execute
    * @param period limiting the max freaquency of execution
    * @throw scidb::UserException if period < 1 or !workItem
    */
   boost::shared_ptr<Scheduler> getScheduler(Scheduler::Work& workItem, time_t period);

   /**
    * Send a message to a node asynchrously
    * @param targetNodeID the node ID of the destination
    * @param msgID a message ID previously registered with NetworkMessageFactory
    * @param record the structured part of the message (derived from ::google::protobuf::Message),
                    the record type must match the one generated by the NetworkMessageFactory
    * @param binary the opaque payload of the message (which can be empty)
    */
   void sendAsync(NodeID targetNodeID,
                  MessageID msgID,
                  MessagePtr record,
                  boost::asio::const_buffer& binary);

   /**
    * @return Time in seconds to wait before decalring a network-silent node dead.
    */
   uint32_t getLivenessTimeout();

} // namespace scidb

#endif /* NETWORK_H_ */
