sudo apt-get -y install libbz2-dev
sudo apt-get -y install libconfig++8-dev 
sudo apt-get -y install libpqxx-dev
sudo apt-get -y install libprotobuf6  
sudo apt-get -y install libprotobuf-dev  
sudo apt-get -y install zlib1g  
sudo apt-get -y install liblog4cxx10-dev 
sudo apt-get -y install libxerces-c-dev
sudo apt-get -y install libboost-all-dev
sudo apt-get -y install libcppunit-dev
sudo apt-get -y install libossp-uuid-dev
sudo apt-get -y install doxygen
sudo apt-get -y install cmake
sudo apt-get -y install flex
sudo apt-get -y install bison
sudo apt-get -y install postgresql
sudo apt-get -y install postgresql-contrib
sudo apt-get -y install g++
